import type { Concept, Source } from './model.ts';

export const sources: Source[] = [
  {
    id: 'bom-mam',
    slug: 'bom-mam',
    name: 'Manual of Aviation Meteorology',
    shortName: 'BOM MAM',
    sourceType: 'textbook',
    reliability: 5,
    jurisdiction: 'au',
    publisher: 'Bureau of Meteorology',
  },
  {
    id: 'bom-aviation',
    slug: 'bom-aviation',
    name: 'Bureau of Meteorology aviation knowledge centre (TAF, METAR/SPECI, SIGMET, AIRMET, fog, thunderstorms, icing, stability guides)',
    shortName: 'BoM aviation',
    sourceType: 'guidelines',
    reliability: 5,
    jurisdiction: 'au',
    publisher: 'Bureau of Meteorology',
  },
  {
    id: 'casa-91-mos',
    slug: 'casa-91-mos',
    name: 'Part 91 (General Operating and Flight Rules) Manual of Standards 2020, compilation F2026C00587',
    shortName: 'Part 91 MOS',
    sourceType: 'guidelines',
    reliability: 5,
    jurisdiction: 'au',
    publisher: 'CASA',
  },
  {
    id: 'casa-121',
    slug: 'casa-121',
    name: 'Part 121 (Australian Air Transport Operations—Larger Aeroplanes) Manual of Standards 2020, compilation F2026C00215',
    shortName: 'Part 121 MOS',
    sourceType: 'guidelines',
    reliability: 5,
    jurisdiction: 'au',
    publisher: 'CASA',
  },
  {
    id: 'casa-ac-121-11',
    slug: 'casa-ac-121-11',
    name: 'Advisory Circular AC 121-11, Part 121 alternate aerodromes',
    shortName: 'AC 121-11',
    sourceType: 'guidelines',
    reliability: 5,
    jurisdiction: 'au',
    publisher: 'CASA',
  },
  {
    id: 'casa-ac-91-15',
    slug: 'casa-ac-91-15',
    name: 'Advisory Circular AC 91-15, Guidelines for aircraft fuel requirements',
    shortName: 'AC 91-15',
    sourceType: 'guidelines',
    reliability: 5,
    jurisdiction: 'au',
    publisher: 'CASA',
  },
  {
    id: 'casa-727',
    slug: 'casa-727',
    name: 'Boeing 727 Performance and Operating Handbook',
    shortName: 'CASA 727',
    sourceType: 'textbook',
    reliability: 5,
    jurisdiction: 'au',
    publisher: 'CASA',
  },
];

/** Sources for the level bank. The ATPL `sources` list stays Australian. */
export const learnSources: Source[] = [
  ...sources,
  { id: 'od-teaching', slug: 'od-teaching', name: 'Operational Decision: original teaching operations sheets', shortName: 'OD teaching manual', sourceType: 'guidelines', reliability: 3, jurisdiction: 'international', publisher: 'Isobar' },
  {
    id: 'faa-acs',
    slug: 'faa-acs',
    name: 'FAA Airman Certification Standards (Private, Commercial, Remote Pilot, ATP)',
    shortName: 'FAA ACS',
    sourceType: 'guidelines',
    reliability: 5,
    jurisdiction: 'international',
    publisher: 'FAA',
  },
  {
    id: 'faa-wx',
    slug: 'faa-wx',
    name: 'Aviation Weather Handbook, FAA-H-8083-28',
    shortName: 'FAA-H-8083-28',
    sourceType: 'textbook',
    reliability: 5,
    jurisdiction: 'international',
    publisher: 'FAA',
  },
  {
    id: 'faa-phak',
    slug: 'faa-phak',
    name: 'Pilot’s Handbook of Aeronautical Knowledge, FAA-H-8083-25',
    shortName: 'PHAK',
    sourceType: 'textbook',
    reliability: 5,
    jurisdiction: 'international',
    publisher: 'FAA',
  },
  {
    id: 'cfr',
    slug: 'cfr',
    name: 'Code of Federal Regulations, Title 14',
    shortName: '14 CFR',
    sourceType: 'guidelines',
    reliability: 5,
    jurisdiction: 'international',
    publisher: 'FAA',
  },
  {
    id: 'casa-101',
    slug: 'casa-101',
    name: 'Part 101 (Unmanned Aircraft and Rockets) Manual of Standards',
    shortName: 'Part 101 MOS',
    sourceType: 'guidelines',
    reliability: 5,
    jurisdiction: 'au',
    publisher: 'CASA',
  },
  {
    id: 'jp-3-59',
    slug: 'jp-3-59',
    name: 'JP 3-59, Meteorological and Oceanographic Operations',
    shortName: 'JP 3-59',
    sourceType: 'guidelines',
    reliability: 5,
    jurisdiction: 'international',
    publisher: 'US Joint Staff',
  },
  {
    id: 'atp-2-01-3',
    slug: 'atp-2-01-3',
    name: 'ATP 2-01.3, Intelligence Preparation of the Battlefield',
    shortName: 'ATP 2-01.3',
    sourceType: 'guidelines',
    reliability: 5,
    jurisdiction: 'international',
    publisher: 'US Army',
  },
];

export const concepts: Concept[] = [
  { id: 'met.taf', name: 'TAF structure', description: 'Decode a routine aerodrome forecast.', subject: 'met', topics: ['taf'], prerequisiteIds: [], examWeight: 5 },
  { id: 'met.taf-change', name: 'FM and BECMG', description: 'Permanent change groups.', subject: 'met', topics: ['taf'], prerequisiteIds: ['met.taf'], examWeight: 4 },
  { id: 'met.taf-tempo', name: 'TEMPO and INTER', description: 'Temporary and intermittent groups.', subject: 'met', topics: ['taf'], prerequisiteIds: ['met.taf'], examWeight: 5 },
  { id: 'met.cavok', name: 'CAVOK and ceiling', description: 'Visibility and ceiling codes.', subject: 'met', topics: ['taf'], prerequisiteIds: ['met.taf'], examWeight: 4 },
  { id: 'met.sigmet', name: 'SIGMET types', description: 'Hazards that warrant a SIGMET.', subject: 'met', topics: ['sigmet'], prerequisiteIds: [], examWeight: 5 },
  { id: 'met.sigmet-time', name: 'SIGMET validity', description: 'How long a SIGMET lasts.', subject: 'met', topics: ['sigmet'], prerequisiteIds: ['met.sigmet'], examWeight: 3 },
  { id: 'met.front', name: 'Fronts, troughs and lows', description: 'Lift from synoptic features in the southern hemisphere.', subject: 'met', topics: ['synoptic'], prerequisiteIds: [], examWeight: 5 },
  { id: 'met.lapse', name: 'Lapse rates', description: 'DALR, SALR and ISA.', subject: 'met', topics: ['stability'], prerequisiteIds: [], examWeight: 4 },
  { id: 'met.stability', name: 'Stability', description: 'Compare the environment with the parcel.', subject: 'met', topics: ['stability'], prerequisiteIds: ['met.lapse'], examWeight: 5 },
  { id: 'met.fog', name: 'Fog', description: 'Fog types and the conditions that make them.', subject: 'met', topics: ['fog'], prerequisiteIds: [], examWeight: 4 },
  { id: 'met.cb', name: 'Cumulonimbus', description: 'Ingredients and triggers for CB.', subject: 'met', topics: ['storm'], prerequisiteIds: ['met.stability'], examWeight: 5 },
  { id: 'met.icing', name: 'Airframe icing', description: 'When ice forms and which kind.', subject: 'met', topics: ['icing'], prerequisiteIds: [], examWeight: 5 },
  { id: 'met.wind', name: 'Geostrophic wind', description: 'Balance of the pressure gradient and Coriolis, southern hemisphere.', subject: 'met', topics: ['wind'], prerequisiteIds: [], examWeight: 5 },
  { id: 'met.gradient', name: 'Gradient wind', description: 'Curved flow and isobar spacing.', subject: 'met', topics: ['wind'], prerequisiteIds: ['met.wind'], examWeight: 4 },
  { id: 'met.qnh', name: 'QNH', description: 'Altimeter subscale.', subject: 'met', topics: ['pressure'], prerequisiteIds: [], examWeight: 3 },
  { id: 'fp.alternate', name: 'Alternate requirement', description: 'When the destination needs an alternate.', subject: 'plan', topics: ['alternate'], prerequisiteIds: [], examWeight: 5 },
  { id: 'fp.holding', name: 'TEMPO and INTER fuel', description: 'Holding fuel in place of an alternate.', subject: 'plan', topics: ['alternate'], prerequisiteIds: ['fp.alternate'], examWeight: 5 },
  { id: 'fp.prob', name: 'PROB groups', description: 'PROB30 and PROB40 in the alternate decision.', subject: 'plan', topics: ['alternate'], prerequisiteIds: ['fp.holding'], examWeight: 4 },
  { id: 'fp.fuel', name: 'Fuel policy', description: 'Part 121 fuel components.', subject: 'plan', topics: ['fuel'], prerequisiteIds: [], examWeight: 5 },
  { id: 'fp.reserve', name: 'Final reserve', description: 'Turbine final reserve, including the 727.', subject: 'plan', topics: ['fuel'], prerequisiteIds: ['fp.fuel'], examWeight: 5 },
  { id: 'fp.contingency', name: 'Contingency and alternate fuel', description: 'The components that are not the reserve.', subject: 'plan', topics: ['fuel'], prerequisiteIds: ['fp.fuel'], examWeight: 4 },
  { id: 'live.today', name: 'Today’s chart', description: 'Read the live snapshot. Missing data skips the card.', subject: 'met', topics: ['live'], prerequisiteIds: [], examWeight: 5 },
  { id: 'fp.later', name: '727 performance', description: 'Handbook numbers, not yet in the deck.', subject: 'plan', topics: ['727'], prerequisiteIds: [], examWeight: 5 },
];
