/** The static deck: Australian ATPL meteorology and flight-planning questions.
 * Every stem is a complete question that puts the pilot in a situation and asks
 * one thing. Every rule-bearing explanation ends with its Australian source;
 * the sections are listed in docs/training/sources.json. Nothing here is a
 * recalled exam item.
 */
import { liveCards } from './live.ts';
import type { Snapshot } from './snapshot.ts';
import type { Card, Citation } from './model.ts';

const mam = (section: string): Citation => ({ sourceId: 'bom-mam', section });
const bom = (section: string): Citation => ({ sourceId: 'bom-aviation', section });
const mos91 = (section: string): Citation => ({ sourceId: 'casa-91-mos', section });
const mos121 = (section: string): Citation => ({ sourceId: 'casa-121', section });
const book727 = (section: string): Citation => ({ sourceId: 'casa-727', section });

function mcq(
  id: string,
  conceptIds: string[],
  subject: Card['subject'],
  stem: string,
  options: string[],
  correct: number,
  explanation: string,
  citations: Citation[],
  planStep: number | null = null,
  complexity: Card['complexity'] = 2,
): Card {
  return {
    id,
    conceptIds,
    subject,
    kind: 'mcq',
    planStep,
    stem,
    options: options.map((text, index) => ({ id: String(index + 1), text })),
    correctId: String(correct + 1),
    explanation,
    citations,
    complexity,
    topics: conceptIds,
  };
}

const TAF_GUIDE = 'BoM aviation TAF guide';
const METAR_GUIDE = 'BoM aviation METAR/SPECI guide';

export const staticCards: Card[] = [
  // --- TAF structure -------------------------------------------------------
  mcq('met.taf.9999', ['met.taf'], 'met',
    'You are planning an arrival into Perth and the TAF group covering your ETA reads 20012KT 9999 SCT030. What visibility are you entitled to plan on?', [
      'At least 10 km',
      'Exactly 9 999 m',
      'Less than 10 km, since 9999 is the lowest value in the band',
      '9 999 ft, converted to about 3 km',
    ], 0,
    `Forecast visibility is given in metres as a four-figure group, and 10 km or more is written 9999, so the group promises at least 10 km. ${TAF_GUIDE}, visibility.`,
    [bom('TAF guide, visibility')], null, 1),
  mcq('met.taf.validity', ['met.taf'], 'met',
    'A Sydney TAF is headed TAF YSSY 062012Z 0621/0800. For which period can you use this forecast?', [
      'From 21:00Z on the 6th to 00:00Z on the 8th',
      'From 20:12Z on the 6th for 27 hours',
      'From 21:00Z on the 6th to 08:00Z on the 7th',
      'From 06:21Z to 08:00Z on the day of issue',
    ], 0,
    `The validity group is day and hour UTC, start and end: 0621/0800 runs from 21:00Z on the 6th to 00:00Z on the 8th. The 062012Z before it is the issue time, which is not the start of validity. ${TAF_GUIDE}, issue time and validity.`,
    [bom('TAF guide, validity')], null, 1),
  mcq('met.taf.wind', ['met.taf'], 'met',
    'The TAF for your destination forecasts wind 18015G25KT at your ETA. How should you read that wind when you work out the crosswind on a magnetic runway heading?', [
      'From 180° true, mean 15 kt, gusting 25 kt, then apply the local variation to compare with the runway',
      'From 180° magnetic, mean 15 kt, gusting 25 kt, directly comparable with the runway number',
      'From 180° true, mean 25 kt with lulls to 15 kt',
      'From 015° true at 18 kt, with the gust factor of 25%',
    ], 0,
    `TAF and METAR wind direction is in degrees true, rounded to 10°, with the mean speed in knots and the gust after G. Runway numbers are magnetic, so the variation has to be applied before the two are compared. ${TAF_GUIDE}, wind.`,
    [bom('TAF guide, wind')]),
  mcq('met.taf.nsw', ['met.taf'], 'met',
    'After a frontal passage a TAF continues FM070900 27012KT 9999 NSW BKN025. What has the forecaster told you with NSW?', [
      'No significant weather is expected after the change, though the cloud and visibility groups still apply',
      'No significant wind, so the 27012KT group can be disregarded',
      'A new south-westerly airstream has arrived behind the front',
      'Nil SIGMET warning is current for the aerodrome',
    ], 0,
    `After an FM or BECMG change, the weather group is replaced by NSW when nil significant weather is expected and CAVOK is not appropriate; the visibility and cloud that follow are still part of the forecast. ${TAF_GUIDE}, weather.`,
    [bom('TAF guide, weather')]),
  mcq('met.taf.prob-place', ['met.taf'], 'met',
    'A TAF includes PROB30 1005/1014 1000 +TSRA BKN040CB. The forecaster has used PROB without INTER or TEMPO. For how long should you expect each thunderstorm deterioration to last, if it occurs?', [
      'An hour or more, because a thunderstorm PROB with no INTER or TEMPO is deemed to last at least an hour',
      'Under 30 minutes, because PROB on its own is the briefest fluctuation',
      'Between 30 and 60 minutes, as for a TEMPO',
      'The whole validity period, because PROB replaces the prevailing group',
    ], 0,
    `When PROB is used with thunderstorms, INTER or TEMPO is added where appropriate to give the probable duration; where PROB is used without one, the likely period of occurrence is deemed to be one hour or more. The guide states this deemed duration for thunderstorms, not for PROB fog. ${TAF_GUIDE}, PROB.`,
    [bom('TAF guide, PROB')]),
  mcq('met.taf.fm', ['met.taf-change'], 'met',
    'A Perth TAF reads 20007KT 9999 SCT008 FM062300 20012KT CAVOK. Arriving at 00:30Z on the 7th, which conditions do you plan on?', [
      'CAVOK with 20012KT, because an FM group replaces everything before it from its time onward',
      'SCT008 with 20007KT, because the base group remains prevailing until the end of the TAF',
      'The worse of the two, because FM marks a period of transition between them',
      'CAVOK only after 00:00Z on the 8th, when the base group period ends',
    ], 0,
    `FM is used when one set of prevailing conditions changes rapidly to another; the new group is a self-contained forecast that applies from that time until the next FM or BECMG or the end of the TAF. ${TAF_GUIDE}, significant changes (FM).`,
    [bom('TAF guide, FM')]),
  mcq('met.taf.becmg', ['met.taf-change'], 'met',
    'A TAF reads 9999 SCT030 BECMG 2620/2622 4000 -RA BKN010. You plan to arrive at 21:00Z, in the middle of the BECMG period. Which conditions must you plan against?', [
      'The deterioration, 4000 m and BKN010, because a BECMG deterioration is applied from the start of its period',
      'The earlier conditions, 9999 and SCT030, because the change is not complete until 22:00Z',
      'Neither, because a BECMG is only a trend and carries no planning weight',
      'An average of the two, because the change is gradual',
    ], 0,
    `BECMG describes a change reached at an unspecified time within the period. For planning, a BECMG deterioration is applied from the start of the period and an improvement only from its end, so at 21:00Z the lower conditions govern. Part 91 MOS 2020 s 8.04 (8); ${TAF_GUIDE}, BECMG.`,
    [mos91('8.04 (8) BECMG deterioration and improvement'), bom('TAF guide, BECMG')]),
  mcq('met.taf.fm-vs-becmg', ['met.taf-change'], 'met',
    'A cold front is expected to cross an aerodrome within a few minutes at about 12:00Z, replacing a northerly with a strong south-westerly. Which indicator would you expect the forecaster to use, and why?', [
      'FM061200, because one set of prevailing conditions changes rapidly to another at a known time',
      'BECMG 0611/0613, because every wind change is written as a gradual one',
      'TEMPO 0611/0613, because a front is a temporary fluctuation',
      'PROB40 0611/0613, because the timing of a front is never certain',
    ], 0,
    `FM is for a rapid change from one set of prevailing conditions to another; BECMG is for a change that reaches the new conditions at a regular or irregular rate at an unspecified time in the period. TEMPO and INTER are variations on the prevailing forecast, not a new prevailing forecast. ${TAF_GUIDE}, significant changes and variations.`,
    [bom('TAF guide, significant changes and variations')]),
  mcq('met.taf.tempo-len', ['met.taf-tempo'], 'met',
    'Your destination TAF carries TEMPO 0612/0618 3000 SHRA BKN010 over a 9999 FEW040 prevailing forecast. If a shower arrives while you are in the hold, how long should you expect the 3000 m and BKN010 to last each time?', [
      '30 minutes or more but less than 60 minutes',
      'Less than 30 minutes',
      'Exactly 60 minutes',
      'The full six hours from 12:00Z to 18:00Z',
    ], 0,
    `TEMPO is for temporary variations lasting 30 minutes or more but less than 60 minutes each; INTER is for variations of less than 30 minutes. The period 0612/0618 is when they may occur, not how long each one lasts. ${TAF_GUIDE}, TEMPO and INTER.`,
    [bom('TAF guide, TEMPO and INTER')]),
  mcq('met.taf.inter-len', ['met.taf-tempo'], 'met',
    'A Perth TAF forecasts INTER 0720/0800 3000 SHRA BKN010. What does INTER tell you about the character of that deterioration?', [
      'Intermittent variations, each lasting less than 30 minutes, within the period 20:00Z to 00:00Z',
      'Temporary variations of 30 to 60 minutes within the period',
      'A steady deterioration that is complete by 00:00Z',
      'An interim forecast that will be replaced by an amendment before 20:00Z',
    ], 0,
    `INTER is used for intermittent variations from the prevailing conditions lasting less than 30 minutes each; TEMPO covers 30 minutes or more but under 60. ${TAF_GUIDE}, TEMPO and INTER.`,
    [bom('TAF guide, TEMPO and INTER')]),
  mcq('met.taf.tempo-not-prevailing', ['met.taf-tempo'], 'met',
    'A TAF reads FM070700 19018KT 9999 -SHRA SCT025 BKN035 INTER 0707/0721 20016G26KT 5000 SHRA BKN013. At 10:00Z, what are the prevailing conditions and what is the INTER group doing?', [
      'Prevailing is the FM070700 group; the INTER lays brief deteriorations to 5000 m and BKN013 over it until 21:00Z',
      'Prevailing is the INTER group, because the later group in the TAF always replaces the earlier',
      'Both groups are prevailing and the worse of each element is the forecast',
      'Neither applies until the INTER period ends at 21:00Z',
    ], 0,
    `The base, FM and BECMG groups set the prevailing conditions. TEMPO and INTER groups are variations laid over the prevailing forecast and apply only within their own period; they do not replace it. ${TAF_GUIDE}, significant changes and variations.`,
    [bom('TAF guide, significant changes and variations')]),

  // --- CAVOK and ceiling ----------------------------------------------------
  mcq('met.cavok.meaning', ['met.cavok'], 'met',
    'A TAF forecasts CAVOK for your arrival at a coastal aerodrome whose highest 25 NM minimum sector altitude is 6 100 ft. Below what height has the forecaster promised no cloud?', [
      'Below 6 100 ft, the higher of 5 000 ft and the highest 25 NM MSA, with no CB or TCU at any height',
      'Below 5 000 ft only, regardless of the MSA',
      'At any height, because CAVOK means a clear sky',
      'Below 1 500 ft, the usual circling height',
    ], 0,
    `CAVOK is forecast when visibility is 10 km or more, there is no cloud below 5 000 ft or below the highest 25 NM minimum sector altitude, whichever is higher, no CB or TCU at any height, and no significant weather. With an MSA of 6 100 ft, the cloud promise reaches 6 100 ft. ${TAF_GUIDE}, CAVOK.`,
    [bom('TAF guide, CAVOK')]),
  mcq('met.cavok.ceiling', ['met.cavok'], 'met',
    'A METAR reports FEW010 SCT018 BKN030 OVC080. You need the ceiling to check the alternate minima. Which layer is it?', [
      'BKN030, the lowest layer covering more than half the sky',
      'FEW010, the lowest layer reported',
      'SCT018, the lowest layer of more than two oktas',
      'OVC080, the first layer covering the whole sky',
    ], 0,
    `The ceiling is the height of the base of the lowest layer below 20 000 ft covering more than half the sky, so BKN (5–7 oktas) or OVC (8 oktas); FEW and SCT do not qualify. ICAO Annex 2 definition adopted by the CASR Dictionary and quoted in Part 121 MOS 2020 s 4.06; ${METAR_GUIDE}, cloud.`,
    [mos121('4.06 note, ceiling definition'), bom('METAR/SPECI guide, cloud')]),
  mcq('met.cavok.bkn', ['met.cavok'], 'met',
    'A TAF group for your ETA reads 9999 -SHRA BKN020. What cloud base does BKN020 forecast?', [
      '2 000 ft above the aerodrome',
      '20 000 ft above the aerodrome',
      '200 ft above the aerodrome',
      '2 000 m above mean sea level',
    ], 0,
    `Cloud height in a TAF or METAR is in hundreds of feet above aerodrome level, so 020 is 2 000 ft. Model and chart heights, by contrast, are above mean sea level. ${TAF_GUIDE}, cloud.`,
    [bom('TAF guide, cloud')], null, 1),
  mcq('met.cavok.sct', ['met.cavok'], 'met',
    'Your destination alternate minimum is a ceiling of 1 500 ft. The TAF forecasts SCT008 BKN025 at your ETA. Does the cloud make an alternate necessary?', [
      'No, because SCT008 is not more than scattered, and the ceiling of 2 500 ft is above the minimum',
      'Yes, because any cloud below the minimum counts against it',
      'Yes, because SCT at 800 ft is a ceiling of 800 ft',
      'No, because cloud is only assessed when the TAF also forecasts rain',
    ], 0,
    `For the alternate decision the relevant cloud condition is more than SCT below the alternate minimum. SCT008 is scattered, so it is not a ceiling; the lowest BKN or OVC layer is 2 500 ft, above the 1 500 ft minimum. Part 91 MOS 2020 s 8.02 (1) (a).`,
    [mos91('8.02 (1) (a) relevant weather conditions, cloud')]),
  mcq('met.cavok.cumulative', ['met.cavok'], 'met',
    'Under Part 121, the TAF for your arrival forecasts FEW008 SCT012 with an alternate ceiling value of 1 500 ft. How must you treat those two layers?', [
      'Add them: FEW plus SCT is treated as BKN, so the cloud is more than SCT below the value',
      'Take only the lowest layer, FEW008, which is not more than SCT',
      'Take only the largest amount, SCT, which is not more than SCT',
      'Ignore both, because layers below 1 000 ft are not assessed',
    ], 0,
    `Part 121 planning treats forecast cloud amounts below the relevant ceiling value as cumulative: FEW plus FEW is SCT, FEW plus SCT is BKN, SCT plus SCT is BKN or OVC. Two thin layers can therefore add to a ceiling. Part 121 MOS 2020 s 4.06 (2).`,
    [mos121('4.06 (2) cumulative cloud amounts')], null, 3),

  // --- TAF3 -------------------------------------------------------------------
  mcq('met.taf.taf3', ['met.taf'], 'met',
    'The Adelaide TAF you are briefed on ends with RMK T 14 15 17 14 Q 1016 1014 1013 1014 TAF3. What does the TAF3 in the remarks tell you about this forecast?', [
      'It is a TAF3: issued every 3 hours and reviewed in depth every hour, with priority amendments',
      'It is a trend forecast valid only for the 3 hours after the latest observation',
      'It is valid for only 3 hours, after which no forecast is available',
      'It is the third amendment of the day, so the earlier two are cancelled',
    ], 0,
    `TAF3 in the remarks marks a TAF3 service: the same code as a TAF, issued routinely every 3 hours, under continuous watch with a scheduled in-depth review every hour and priority amendments. It is provided 24/7 at the major airports, Adelaide among them; a VALID TL time marks the end of a limited service. ${TAF_GUIDE}, TAF3.`,
    [bom('TAF guide, TAF3')], null, 1),

  // --- SIGMET -----------------------------------------------------------------
  mcq('met.sig.turb', ['met.sigmet'], 'met',
    'En route you are briefed moderate turbulence below 10 000 ft on the GAF and no SIGMET. A colleague asks why the turbulence did not warrant a SIGMET. What do you tell them?', [
      'A SIGMET for turbulence is issued only when it is severe; moderate turbulence belongs on the GAF, or in an AIRMET if the GAF omits it',
      'A SIGMET is issued for any turbulence once it is forecast for more than four hours',
      'A SIGMET is only for turbulence above 10 000 ft',
      'A SIGMET requires a pilot report before it can be issued',
    ], 0,
    `SIGMETs cover obscured, embedded, frequent or squall-line thunderstorms, severe turbulence, severe icing, severe mountain waves, heavy duststorm or sandstorm, volcanic ash, tropical cyclone and radioactive cloud; moderate turbulence is not on the list. Moderate turbulence below 10 000 ft that the GAF does not already include is issued as an AIRMET. BoM aviation SIGMET guide, phenomena; BoM aviation AIRMET guide.`,
    [bom('SIGMET guide, phenomena'), bom('AIRMET guide, phenomena')]),
  mcq('met.sig.ts', ['met.sigmet'], 'met',
    'Isolated thunderstorms are forecast along your route in the GAF, but there is no SIGMET. Does that mean the forecaster expects no thunderstorms?', [
      'No. Storms do not warrant a SIGMET just by existing; only obscured, embedded, frequent or squall-line storms do',
      'Yes. Any thunderstorm in the area would require a SIGMET',
      'No. SIGMETs are only issued for thunderstorms over the sea',
      'Yes. The GAF entry is withdrawn automatically when a SIGMET is not issued',
    ], 0,
    `Thunderstorm SIGMETs are issued only when storms are obscured by haze or smoke, embedded in cloud layers, frequent (little separation, over 75% of the area) or in a squall line of about 100 NM or more. Isolated storms in clear view are forecast on the GAF, and isolated or occasional storms below 10 000 ft that the GAF does not include are issued as an AIRMET. BoM aviation SIGMET guide, thunderstorms; BoM aviation AIRMET guide.`,
    [bom('SIGMET guide, thunderstorms'), bom('AIRMET guide, phenomena')]),
  mcq('met.sig.ice', ['met.sigmet'], 'met',
    'A SIGMET on your route includes SEV ICE (FZRA) and levels 2000/8000FT. What has been forecast, and why does the bracket matter to you?', [
      'Severe icing from freezing rain between 2 000 and 8 000 ft, the kind that builds clear ice fastest',
      'Moderate icing in rain between 2 000 and 8 000 ft',
      'Severe icing only in cloud, with freezing rain excluded',
      'Carburettor icing in the freezing level band',
    ], 0,
    `An icing SIGMET is for severe icing only. SEV ICE (FZRA) names freezing rain as the cause: large supercooled drops that spread before freezing, so clear ice accretes quickly on any surface at or below 0 °C. BoM aviation SIGMET guide, phenomena; BoM aviation icing guide.`,
    [bom('SIGMET guide, phenomena'), bom('Icing guide, clear ice and freezing rain')]),
  mcq('met.sig.va', ['met.sigmet'], 'met',
    'Volcanic ash from an eruption is drifting into the Brisbane FIR. In which message should you expect the warning for en-route aircraft?', [
      'A volcanic ash SIGMET for the FIR, valid for up to six hours',
      'A TEMPO group in each affected TAF',
      'A remark on the hourly METARs along the route',
      'An INTER group in the GAF',
    ], 0,
    `Volcanic ash is one of the SIGMET phenomena and gets its own SIGMET, which, like a tropical cyclone SIGMET, may be valid for up to six hours rather than four. TAF and METAR groups do not carry an en-route ash warning. BoM aviation SIGMET guide, phenomena and validity.`,
    [bom('SIGMET guide, validity')]),
  mcq('met.sig.4h', ['met.sigmet-time'], 'met',
    'A severe turbulence SIGMET for the Melbourne FIR is VALID 062245/070245. Your flight through the area is at 03:30Z on the 7th. Can you assume the hazard has gone?', [
      'No. The SIGMET has simply reached its four-hour maximum validity; a further SIGMET may follow and the hazard must be rebriefed',
      'Yes. A SIGMET expiring without a cancellation means the phenomenon has ended',
      'Yes. Severe turbulence never lasts more than four hours',
      'No. A weather SIGMET remains in force for 24 hours from issue',
    ], 0,
    `A SIGMET for weather other than volcanic ash or a tropical cyclone cannot be valid for more than four hours, so an expiry is a renewal point, not a declaration that the hazard is over. A SIGMET that is no longer warranted is cancelled explicitly. BoM aviation SIGMET guide, validity.`,
    [bom('SIGMET guide, validity')]),
  mcq('met.sig.6h', ['met.sigmet-time'], 'met',
    'Which SIGMETs may be issued with a validity of up to six hours rather than four?', [
      'Volcanic ash and tropical cyclone SIGMETs',
      'Severe turbulence and severe icing SIGMETs',
      'Thunderstorm SIGMETs in the tropics',
      'Any SIGMET issued at night',
    ], 0,
    `The validity period of a SIGMET cannot exceed six hours for volcanic ash and tropical cyclone, and four hours for every other phenomenon. BoM aviation SIGMET guide, validity.`,
    [bom('SIGMET guide, validity')]),

  // --- Fronts, troughs and lows ---------------------------------------------
  mcq('met.front.cold', ['met.front'], 'met',
    'A winter cold front is approaching Perth from the south-west. Why does the chart ahead of the front so often bring thunderstorms and squally showers rather than steady rain?', [
      'The dense cold air undercuts the warmer air ahead, lifting it steeply and releasing conditional instability',
      'The warm air glides gently up over the cold air, giving a shallow slope and stratiform cloud',
      'Air sinks in the ridge behind the front and warms, drying the lower levels',
      'The front is a line of equal pressure, so there is no vertical motion at all',
    ], 0,
    `A cold front is dense air advancing under warmer air. The lift is steep and sudden, so moist, conditionally unstable air is released into cumulus and cumulonimbus, often with a pre-frontal trough or squall line ahead. BoM aviation flying the south-west guide, cold fronts; BoM Manual of Aviation Meteorology, fronts.`,
    [bom('Flying the south-west guide, cold fronts'), mam('Fronts and depressions')]),
  mcq('met.front.warm', ['met.front'], 'met',
    'Ahead of a warm front the cloud thickens from cirrus to altostratus to nimbostratus over several hundred kilometres, with a steadily lowering base. Why does a warm front produce this layered sequence rather than cumulonimbus?', [
      'The warm air overruns the cold air on a shallow slope, so the lift is gentle and widespread and the cloud is stratiform',
      'The cold air undercuts the warm air steeply, so the cloud is forced into layers',
      'Warm fronts only occur over the sea, where there is no surface heating to trigger convection',
      'The warm air is always absolutely stable, so no cumulus can form anywhere near it',
    ], 0,
    `In a warm front the warm air rides up a long shallow wedge of cold air. The ascent is slow and spread over a wide area, which gives layered cloud, lowering bases and prolonged precipitation, with poor visibility in rain and mist. BoM Manual of Aviation Meteorology, fronts and depressions.`,
    [mam('Fronts and depressions')]),
  mcq('met.front.back', ['met.front'], 'met',
    'A cold front passes Sydney and the wind changes from north-westerly to south-westerly. In the southern hemisphere, how is that change described, and why?', [
      'Backing, because the direction moves anticlockwise, from 315° through west to 225°',
      'Veering, because the direction moves clockwise through south',
      'Backing, because any frontal change is a backing change',
      'Veering, because that is the rule shown in most textbook frontal diagrams',
    ], 0,
    `Backing is an anticlockwise change of direction; veering is clockwise. A north-west to south-west change moves through west, from 315° to 225°, which is anticlockwise. Southern hemisphere cold fronts back the wind; northern hemisphere diagrams, where the same front veers the wind, do not apply here. BoM aviation glossary, backing and veering; BoM Manual of Aviation Meteorology, fronts.`,
    [bom('Glossary, backing and veering'), mam('Fronts and depressions')]),
  mcq('met.front.trough', ['met.front'], 'met',
    'On a summer MSLP chart the isobars over the Western Australian coast bend into a sharp V pointing away from the low, towards higher pressure, along a line from inland to just offshore, with no front drawn. What is the feature, and why does it matter for your flight?', [
      'A trough: an elongated area of low pressure where air converges and rises, so cloud, showers and thunderstorms can form along it',
      'A ridge: an elongated area of high pressure where air subsides, so the weather is fine',
      'A col: a saddle between two highs, where the wind is light and variable',
      'A jet-stream axis drawn at the surface, giving strong winds but no weather',
    ], 0,
    `A trough is an elongated area of low pressure. Surface air converges into it and rises, which is why the west coast trough is a summer trigger for low cloud, showers and thunderstorms even without a front. BoM aviation glossary, trough; BoM aviation flying the south-west guide, west coast trough.`,
    [bom('Glossary, trough'), bom('Flying the south-west guide, low cloud and thunderstorms')]),
  mcq('met.front.low', ['met.front'], 'met',
    'The MSLP chart shows a deep low centred south of Tasmania. Flying over Bass Strait, north of the centre, what surface wind direction should you expect, and why?', [
      'Westerly, because air circulates clockwise around a southern hemisphere low',
      'Easterly, because air circulates anticlockwise around a southern hemisphere low',
      'Northerly, because the wind always blows towards the centre of a low',
      'Calm, because the pressure gradient north of a low is weak',
    ], 0,
    `In the southern hemisphere air circulates clockwise around a low and anticlockwise around a high, with a slight inflow across the isobars near the surface. North of a low the clockwise circulation gives a westerly, which is why Bass Strait is windy when a low sits south of Tasmania. BoM aviation glossary, cyclonic circulation; BoM Manual of Aviation Meteorology, wind.`,
    [bom('Glossary, cyclone and anticyclone'), mam('Wind')]),
  mcq('met.front.seabreeze', ['met.front'], 'met',
    'On a hot Perth afternoon the wind at the airport swings from a light easterly to a fresh south-westerly by mid-afternoon with a small temperature drop. What has happened, and why?', [
      'A sea breeze has set in: the land heated faster than the sea, so cooler, denser sea air moved inshore under the rising air over the land',
      'A cold front has passed, undercutting the warm air with a deep layer of polar air',
      'The subtropical ridge has moved over the coast, reversing the gradient wind',
      'A land breeze has set in, driven by the sea cooling faster than the land',
    ], 0,
    `A sea breeze is a diurnal onshore wind driven by the temperature difference between land and water: the land warms faster, air rises over it, and cooler marine air flows in beneath, often with a sea-breeze front marked by a drop in temperature and rise in humidity. Perth's afternoon south-westerly is the classic example. BoM aviation glossary, sea breeze and sea-breeze front.`,
    [bom('Glossary, sea breeze')]),

  // --- Lapse rates and stability ---------------------------------------------
  mcq('met.lapse.dalr', ['met.lapse'], 'met',
    'Surface air at 30 °C is forced up a 3 000 ft escarpment without reaching saturation. About what temperature does it reach the top, and why?', [
      'About 21 °C, because unsaturated air cools at the dry adiabatic rate of about 3 °C per 1 000 ft',
      'About 25.5 °C, because rising air cools at the saturated rate of about 1.5 °C per 1 000 ft',
      'About 24 °C, because all rising air follows the ISA rate of about 2 °C per 1 000 ft',
      'About 30 °C, because the air exchanges heat with the hillside and stays at surface temperature',
    ], 0,
    `A rising unsaturated parcel expands and cools adiabatically at the dry adiabatic lapse rate, about 3 °C per 1 000 ft: 30 − 9 = 21 °C. The saturated rate applies only once condensation begins, and ISA describes the standard environment, not a parcel. BoM aviation atmospheric stability guide, lapse rates.`,
    [bom('Atmospheric stability guide, lapse rates')]),
  mcq('met.lapse.salr', ['met.lapse'], 'met',
    'Once a rising parcel reaches its dew point and cloud forms, it cools more slowly, at roughly 1.5 °C per 1 000 ft in the lower troposphere. Why does saturation slow the cooling?', [
      'Condensation releases latent heat into the parcel, offsetting part of the expansion cooling',
      'Cloud droplets absorb sunlight and warm the parcel directly',
      'Saturated air is denser, so it expands less as it rises',
      'The parcel stops rising at the cloud base, so it stops cooling',
    ], 0,
    `The saturated adiabatic lapse rate is less than the dry rate because water vapour condensing in the parcel releases latent heat, which replaces some of the heat lost to expansion. The rate is not constant: it is lowest in warm, moist air and approaches the dry rate at very cold temperatures. BoM aviation atmospheric stability guide, lapse rates.`,
    [bom('Atmospheric stability guide, lapse rates')]),
  mcq('met.lapse.isa', ['met.lapse'], 'met',
    'Your performance charts are referenced to ISA, and today the 10 000 ft temperature is +5 °C. By how much is the air warmer than ISA at that level, taking ISA sea level as 15 °C?', [
      'About 10 °C, because ISA falls at 1.98 °C per 1 000 ft to about −5 °C at 10 000 ft',
      'About 20 °C, because ISA falls at 3 °C per 1 000 ft to −15 °C',
      'About 5 °C, because ISA falls at 1.5 °C per 1 000 ft to 0 °C',
      'Nothing, because +5 °C is the ISA temperature at 10 000 ft',
    ], 0,
    `The International Standard Atmosphere has 15 °C at sea level falling 1.98 °C per 1 000 ft to the tropopause, so about −5 °C at 10 000 ft; +5 °C is ISA +10. The ISA lapse is a reference environment and is not the rate at which a real parcel cools. BoM Manual of Aviation Meteorology, the standard atmosphere.`,
    [mam('The atmosphere: ISA')]),
  mcq('met.stab.abs', ['met.stability'], 'met',
    'A morning sounding over Sydney shows the temperature falling only 1 °C per 1 000 ft through the lowest 5 000 ft. What does that tell you about convection today, and why?', [
      'The layer is absolutely stable: a lifted parcel, dry or saturated, cools faster than its surroundings, so it sinks back and convection is suppressed',
      'The layer is absolutely unstable: a lifted parcel stays warmer than its surroundings and keeps rising',
      'The layer is conditionally unstable: dry parcels sink back but saturated parcels keep rising',
      'The layer is neutral: a parcel displaced up or down simply stays where it is put',
    ], 0,
    `An environmental lapse rate smaller than the saturated adiabatic rate (about 1.5 °C per 1 000 ft) is absolutely stable: whether a parcel cools at the dry or the saturated rate it ends up cooler and denser than the air around it and returns to its level. BoM aviation atmospheric stability guide, determining stability.`,
    [bom('Atmospheric stability guide, determining stability')]),
  mcq('met.stab.cond', ['met.stability'], 'met',
    'The environmental lapse rate over an inland aerodrome is 2.2 °C per 1 000 ft. Fair-weather cumulus is forecast only in the afternoon, when moist air is lifted by heating. Why does the forecaster call this conditionally unstable?', [
      'The rate lies between the saturated and dry adiabatic rates, so a dry parcel sinks back but a parcel that saturates keeps rising',
      'The rate exceeds the dry adiabatic rate, so any parcel rises whether or not it saturates',
      'The rate is below the saturated adiabatic rate, so convection depends entirely on the trigger',
      'The condition refers to the forecaster\u2019s confidence, not to the lapse rate',
    ], 0,
    `Conditional instability is an environmental lapse rate between the saturated rate (about 1.5 °C per 1 000 ft) and the dry rate (about 3 °C per 1 000 ft). An unsaturated parcel cools faster than the environment and sinks back; once it is lifted to saturation it cools more slowly than the environment and becomes buoyant. The condition is saturation, which needs moisture and a trigger. BoM aviation atmospheric stability guide, conditional instability.`,
    [bom('Atmospheric stability guide, conditional instability')]),
  mcq('met.stab.unstable', ['met.stability'], 'met',
    'Over a hot inland plain in the afternoon the lowest 3 000 ft cools at 3.5 °C per 1 000 ft. Why does this layer produce vigorous thermals and turbulence?', [
      'The environment cools faster than the dry adiabatic rate, so even an unsaturated parcel stays warmer than its surroundings and accelerates upward',
      'The environment cools more slowly than the saturated rate, so parcels sink and the air churns',
      'The air is at the ISA lapse rate, which is always turbulent',
      'The layer is isothermal, so the parcel has nothing to compare itself with',
    ], 0,
    `An environmental lapse rate greater than the dry adiabatic rate (about 3 °C per 1 000 ft) is absolutely unstable: a parcel displaced upward cools more slowly than the air it rises into, remains warmer and less dense, and keeps going. Strong surface heating makes such superadiabatic layers over inland Australia. BoM aviation atmospheric stability guide, determining stability.`,
    [bom('Atmospheric stability guide, determining stability')]),

  // --- Fog ----------------------------------------------------------------------
  mcq('met.fog.rad', ['met.fog'], 'met',
    'A winter high is settling over the south-west after a front. The Perth evening METAR shows 15/13, wind 3 kt and a clear sky. Why should you expect fog by dawn?', [
      'The ground will radiate heat to a clear sky, cooling the moist air to its dew point, and the light wind will mix that cooling through a shallow layer',
      'The strong subsidence in the high will force moist air down to the surface and saturate it',
      'The dew point will rise overnight as the sea breeze brings in more moisture',
      'The light wind means the air is calm enough for frost, and frost always becomes fog',
    ], 0,
    `Radiation fog needs a clear night, moist air and light winds, generally 5 kt or less: the surface cools by radiation, the air above it reaches dew point, and a light wind spreads the cooling into a shallow layer. A 2 °C dew-point spread and 3 kt under a clear sky are the setup, and the post-frontal ridge gives the clear sky and the moisture. BoM aviation fog guide, radiation fog; BoM aviation flying the south-west guide, fog.`,
    [bom('Fog guide, radiation fog'), bom('Flying the south-west guide, fog')]),
  mcq('met.fog.adv', ['met.fog'], 'met',
    'Sea fog rolls in over a coastal aerodrome in the afternoon with a 12 kt onshore wind and does not clear with the heat of the day. Why is this fog different from radiation fog?', [
      'It is advection fog: warm moist air moving over a colder sea surface is cooled to its dew point, so it needs wind and persists while that flow continues',
      'It is radiation fog that formed over the sea at night and was blown inland',
      'It is steam fog from cold air over warm water, which deepens with wind',
      'It is frontal fog from rain falling into cold air ahead of a warm front',
    ], 0,
    `Advection fog forms when warm moist air moves over a colder surface and is cooled to its dew point. It needs some turbulence, typically 6–18 kt, to deepen, and unlike radiation fog it can form and persist by day and in moderate wind while the airflow continues. Sea fogs are usually advection fogs. BoM aviation fog guide, advection fog.`,
    [bom('Fog guide, advection fog')]),
  mcq('met.fog.steam', ['met.fog'], 'met',
    'On a cold, clear winter morning wisps of fog rise from the surface of a river beside an aerodrome. What is forming, and why?', [
      'Steam fog: the cold air over the warmer water is saturated by evaporation from the water surface',
      'Radiation fog: the river cools the air above it faster than the land does',
      'Advection fog: warm river air is moving over the colder ground',
      'Frontal fog: rain has evaporated into the cold air above the river',
    ], 0,
    `Steam fog is caused by evaporation from a water surface into much colder air lying over it; the vapour saturates the cold air and condenses, and convection above the water gives the steaming look. It is the reverse of advection fog, where the surface is the cold element. BoM aviation fog guide, steam fog.`,
    [bom('Fog guide, steam fog')]),
  mcq('met.fog.front', ['met.fog'], 'met',
    'Steady rain has fallen for hours ahead of a front and the visibility beneath the cloud falls to a few hundred metres in fog, even though the wind is 10 kt. What is the mechanism?', [
      'Precipitation fog: rain falling from warmer air evaporates into the cooler air below, raising its dew point until it saturates',
      'Radiation fog: the rain cools the ground, which cools the air by radiation',
      'Advection fog: the rain-cooled air is moving over warmer ground',
      'Steam fog: the wet ground is warmer than the air above it',
    ], 0,
    `Precipitation (frontal) fog forms when rain or drizzle falling from relatively warm air evaporates into cooler air near the surface, adding moisture until the air saturates. Unlike radiation fog it goes with overcast skies, precipitation and a wind, and the air above it is also poor. BoM aviation fog guide, precipitation fog.`,
    [bom('Fog guide, precipitation fog')]),

  // --- Cumulonimbus -------------------------------------------------------------
  mcq('met.cb.three', ['met.cb'], 'met',
    'The afternoon sounding over Darwin is deeply unstable, yet no storms form until the sea breeze pushes inland at about 15:00 local. Which ingredient was missing until then?', [
      'A lifting mechanism: instability and moisture were present but nothing had forced the air up to its level of free convection',
      'Moisture: the sea breeze brought in the first humid air of the day',
      'Instability: the sea breeze steepened the lapse rate',
      'A freezing level low enough for hail to form',
    ], 0,
    `A thunderstorm needs three ingredients together: an unstable atmosphere, sufficient low-level moisture, and a lifting mechanism to start the air rising. Sea-breeze fronts, cold and warm fronts, pre-frontal and easterly troughs, terrain and storm outflows are the common triggers. BoM aviation thunderstorms guide, ingredients and triggers.`,
    [bom('Thunderstorms guide, ingredients and triggers')]),
  mcq('met.cb.trigger', ['met.cb'], 'met',
    'A vigorous winter cold front is forecast to cross the far south-west of Western Australia. Why does the forecaster expect thunderstorms with this front when summer fronts there often pass dry?', [
      'The front lifts moist, conditionally unstable maritime air steeply, releasing instability that needs only a trigger',
      'Winter fronts are warmer than summer fronts, so they carry more energy',
      'The front lowers the dry adiabatic lapse rate, making all air unstable',
      'Winter fronts always produce thunderstorms, regardless of the air mass',
    ], 0,
    `In the far south-west, winter thunderstorms are most often associated with cold fronts: the front is the lifting mechanism, acting on moist, conditionally unstable air in the cold southerly stream. The lapse rate and moisture still have to support the parcel; the front only starts it. BoM aviation flying the south-west guide, thunderstorms; BoM aviation thunderstorms guide, triggers.`,
    [bom('Flying the south-west guide, thunderstorms'), bom('Thunderstorms guide, ingredients and triggers')]),
  mcq('met.cb.cape', ['met.cb'], 'met',
    'A model sounding gives MUCAPE of 2 500 J/kg over an inland aerodrome, but the TAF has no thunderstorm. How should you read the CAPE figure?', [
      'As the buoyant energy available to the most unstable parcel if it is lifted: large instability, but not by itself a forecast of a storm',
      'As a thunderstorm forecast: any CAPE above 1 000 J/kg means storms will form',
      'As a cloud base in feet, which here is far above the aerodrome',
      'As a wind-shear index, which if large prevents storms',
    ], 0,
    `CAPE is the energy per kilogram that buoyancy would give a parcel rising from its level of free convection to its equilibrium level, so it measures instability alone. The thunderstorms guide names three ingredients: instability, moisture and a lifting mechanism; without the lift, or the moisture, no storm forms. BoM aviation thunderstorms guide, ingredients.`,
    [bom('Thunderstorms guide, ingredients and triggers')]),
  mcq('met.cb.gustfront', ['met.cb'], 'met',
    'On final approach beneath a mature thunderstorm you meet a strong headwind, then a sink, then a strong tailwind, and the airspeed surges then decays. What has the aircraft flown through, and why is it dangerous?', [
      'A downburst: a concentrated downdraft spreading out at the ground, so a pilot who corrects for the headwind lift can lose height fast in the downdraft and tailwind',
      'The gust front: the boundary of the outflow, which gives a single sharp wind shift but no downdraft or tailwind',
      'The updraught core: warm air rising into the storm, which lifts the aircraft smoothly above the glidepath',
      'The anvil outflow: high-level ice crystals falling into the approach path',
    ], 0,
    `Downburst winds start at cloud base and diverge on reaching the ground, so an aircraft first meets a strong headwind, then the descending downdraft, then a strong tailwind; overcorrecting for the headwind lift can cause a dangerous loss of height. The guide distinguishes these concentrated downdrafts from the broader gust front at the edge of the outflow. BoM aviation thunderstorms guide, downbursts.`,
    [bom('Thunderstorms guide, downbursts')]),

  // --- Icing ----------------------------------------------------------------------
  mcq('met.ice.need', ['met.icing'], 'met',
    'Cruising in clear air at FL180 the outside air temperature is −12 °C and the airframe collects no ice. Entering a cloud layer at the same temperature, ice builds quickly. What changed?', [
      'The aircraft met supercooled liquid water: droplet icing needs visible moisture as well as a surface at or below 0 °C',
      'The temperature inside cloud is always lower than outside it',
      'The cloud shielded the airframe from the sun, letting it cool below freezing',
      'The pitot heat failed as the aircraft entered cloud',
    ], 0,
    `Rime and clear ice form when supercooled liquid droplets, water still liquid below 0 °C, strike a surface at or below 0 °C and freeze on it; cold clear air has no droplets, while cloud and precipitation do. Hoar frost is the exception: it can form in clear air when a cold-soaked aircraft passes into warmer, moist air. BoM aviation icing guide, formation and hoar frost.`,
    [bom('Icing guide, formation and hoar frost')]),
  mcq('met.ice.clear', ['met.icing'], 'met',
    'Climbing through the tops of cumulus at −6 °C the leading edges glaze over quickly with hard, transparent ice that runs back beyond the de-icing boots. Why does this cloud give clear ice rather than rime?', [
      'Large supercooled drops near 0 to −10 °C spread back over the surface before they freeze, forming a dense transparent layer',
      'Tiny droplets at −20 °C freeze instantly on impact, trapping air and forming a transparent layer',
      'Ice crystals in the cloud melt on the warm leading edge and refreeze behind it',
      'Clear ice can only form in freezing rain, so this must be rain from above',
    ], 0,
    `Clear ice forms when large supercooled droplets, most common between 0 and −10 °C in cumuliform cloud and in freezing rain, spread over the surface before freezing. The result is a hard, glassy, heavy deposit that runs back beyond protected areas. Small droplets at colder temperatures freeze on impact as rime instead. BoM aviation icing guide, clear ice.`,
    [bom('Icing guide, clear ice')]),
  mcq('met.ice.rime', ['met.icing'], 'met',
    'In stratiform cloud at −15 °C a rough, milky deposit builds slowly on the leading edges. Why does this cloud give rime rather than clear ice?', [
      'Small supercooled droplets freeze on impact, trapping air between them, which makes the deposit opaque and brittle',
      'Large droplets spread back before freezing, which traps air in the layer',
      'Snow is sticking to the wing and compacting into ice',
      'The temperature is too warm for clear ice, which needs −20 °C or colder',
    ], 0,
    `Rime ice forms from small supercooled droplets that freeze almost instantly on contact, trapping air and producing a white, opaque, brittle deposit. It is typical of stratiform cloud in the −10 to −20 °C range, where droplets are small. Larger droplets nearer 0 °C give clear ice. BoM aviation icing guide, rime ice.`,
    [bom('Icing guide, rime ice')]),
  mcq('met.ice.zr', ['met.icing'], 'met',
    'Descending through a warm frontal zone you encounter rain at −2 °C below a layer of warmer air aloft, and ice builds faster than you have ever seen it. What is happening, and why is it severe?', [
      'Freezing rain: large drops fall from above-freezing air into sub-zero air, stay liquid as supercooled drops, and freeze as clear ice on contact',
      'Sleet: the rain is freezing into ice pellets in the air, which bounce off the airframe',
      'Rime: tiny droplets are freezing instantly on impact',
      'Hoar frost: water vapour is depositing directly as ice on the cold airframe',
    ], 0,
    `Freezing rain occurs when rain falls from a warmer layer into air below 0 °C and becomes supercooled. The drops are large and the water content is high, so clear ice accretes very quickly, which is why SEV ICE (FZRA) has its own SIGMET wording. Severe icing calls for an immediate change of heading or altitude, or both. BoM aviation icing guide, freezing rain and pilot actions; BoM aviation SIGMET guide, phenomena.`,
    [bom('Icing guide, freezing rain'), bom('SIGMET guide, phenomena')]),

  // --- Wind -----------------------------------------------------------------------
  mcq('met.wind.balance', ['met.wind'], 'met',
    'Above the friction layer, with straight isobars, the wind blows parallel to the isobars rather than from high to low pressure. Which two forces are in balance to make that happen?', [
      'The pressure gradient force and the Coriolis force',
      'The pressure gradient force and friction',
      'The Coriolis force and the centrifugal force',
      'Gravity and the pressure gradient force',
    ], 0,
    `The geostrophic wind is the balance of the horizontal pressure gradient force, which points towards low pressure, and the Coriolis force, which acts at right angles to the motion. Once balanced, the air moves along the isobars. Friction enters only near the surface, and the centrifugal term only when the isobars curve. BoM aviation glossary, geostrophic wind.`,
    [bom('Glossary, geostrophic wind')]),
  mcq('met.wind.buys', ['met.wind'], 'met',
    'You are flying over inland New South Wales with a strong wind directly on your tail. Where is the low pressure, and why does the rule differ from the one in a northern hemisphere textbook?', [
      'On your right, because the Coriolis force deflects moving air to the left in the southern hemisphere',
      'On your left, because Buys Ballot\u2019s law is the same in both hemispheres',
      'Directly ahead, because the wind blows straight towards low pressure',
      'Directly behind, because the wind blows straight out of a low',
    ], 0,
    `Buys Ballot's law: with your back to the wind, low pressure is on your left in the northern hemisphere and on your right in the southern hemisphere, because Coriolis deflection is to the left south of the equator. Northern hemisphere diagrams put the low on the wrong side for Australia. BoM aviation glossary, Buys Ballot's law.`,
    [bom('Glossary, Buys Ballot\u2019s law')]),
  mcq('met.wind.spacing', ['met.wind'], 'met',
    'On today\u2019s chart the isobars over Bass Strait are half as far apart as those over the Great Australian Bight, at about the same latitude. What does that tell you about the wind over Bass Strait?', [
      'The geostrophic wind is about twice as strong, because the pressure gradient force is about twice as large',
      'The wind is about half as strong, because closely spaced isobars mark light winds near a high',
      'The wind is the same, because at the same latitude the Coriolis force fixes the speed',
      'Nothing, because isobar spacing shows pressure, not wind',
    ], 0,
    `Isobar spacing is the pressure gradient. At a given latitude the geostrophic wind is proportional to that gradient, since a larger pressure gradient force needs a faster wind for the Coriolis force to balance it. Halving the spacing roughly doubles the wind. BoM aviation glossary, geostrophic wind; BoM Manual of Aviation Meteorology, wind.`,
    [bom('Glossary, geostrophic wind'), mam('Wind')], null, 1),
  mcq('met.wind.friction', ['met.wind'], 'met',
    'The 3 000 ft wind over Sydney is 240° at 35 kt but the surface wind is 270° at 20 kt. Why is the surface wind weaker and from a different direction?', [
      'Friction slows the air, which weakens the Coriolis force, so the pressure gradient force turns the wind towards lower pressure: in the southern hemisphere the surface wind is veered from the gradient wind',
      'The surface wind is thermal, driven by heating of the ground, and unrelated to the gradient wind',
      'Friction adds a force along the wind, speeding it up near the ground but turning it',
      'The Coriolis force reverses near the surface, swinging the wind the other way',
    ], 0,
    `Surface friction reduces wind speed. The Coriolis force depends on speed, so it falls, and the pressure gradient force is no longer balanced: the wind crosses the isobars towards low pressure. With the low on the right of the wind in the southern hemisphere (Buys Ballot), that turn is clockwise, so the surface wind is veered from the gradient wind, typically by 20–30° over land, and backs again as you climb out of the friction layer. BoM aviation glossary, Buys Ballot\u2019s law; BoM Manual of Aviation Meteorology, wind in the friction layer.`,
    [mam('Wind: the friction layer')]),

  // --- Gradient wind --------------------------------------------------------------
  mcq('met.grad.cyclo', ['met.gradient'], 'met',
    'Around a deep low the isobars are tightly curved. For the same isobar spacing, is the actual wind faster or slower than the geostrophic value, and why?', [
      'Slower, because the centrifugal force acts outward with the Coriolis force, so a smaller speed balances the same pressure gradient',
      'Faster, because the centrifugal force adds to the pressure gradient force',
      'The same, because curvature does not enter the balance of forces',
      'Slower, because lows are always surrounded by friction',
    ], 0,
    `The gradient wind includes the centrifugal force. Around a low the pressure gradient force points inward and the centrifugal and Coriolis forces both point outward, so the Coriolis force, and with it the speed, needs to be smaller than in the straight-isobar case: cyclonic flow is subgeostrophic. The rule holds in both hemispheres. BoM aviation glossary, gradient wind; BoM Manual of Aviation Meteorology, wind.`,
    [bom('Glossary, gradient wind'), mam('Wind')]),
  mcq('met.grad.anti', ['met.gradient'], 'met',
    'Around a large high the isobars curve the other way. For the same spacing, how does the gradient wind compare with the geostrophic wind, and why?', [
      'Faster, because the Coriolis force must balance both the outward pressure gradient force and the outward centrifugal force',
      'Slower, because highs are regions of light wind by definition',
      'The same, because the centrifugal force is zero around a high',
      'Reversed, because the pressure gradient force points outward',
    ], 0,
    `Around a high the pressure gradient force points outward and the centrifugal force also acts outward, so the inward Coriolis force must balance both. A larger Coriolis force means a faster wind: anticyclonic flow is supergeostrophic. In practice highs have weak gradients, so the winds are still light. BoM aviation glossary, gradient wind; BoM Manual of Aviation Meteorology, wind.`,
    [bom('Glossary, gradient wind'), mam('Wind')]),
  mcq('met.grad.where', ['met.gradient'], 'met',
    'Looking at today\u2019s MSLP chart, where should you expect the strongest surface winds, and why?', [
      'Where the isobars are closest together, because the spacing shows the pressure gradient that drives the wind',
      'Where the isobars are farthest apart, because open spacing marks a strong airstream',
      'At the centre of the high, where the pressure is greatest',
      'Along the coastline, because land and sea always generate wind',
    ], 0,
    `The pressure gradient is the change of pressure over distance, which on a chart is the isobar spacing; tightly packed isobars mean a large gradient and a strong wind. Pressure value alone says nothing about wind, and the centre of a high is the calmest place on the chart. BoM Manual of Aviation Meteorology, wind.`,
    [mam('Wind')], null, 1),

  // --- QNH -----------------------------------------------------------------------
  mcq('met.qnh.what', ['met.qnh'], 'met',
    'Before an IFR departure from Perth, elevation 67 ft, you set the accurate ATIS QNH and the altimeter reads 17 ft. Is that altimeter usable for the flight?', [
      'Yes. With QNH set it should read the 67 ft elevation, and a 50 ft error is within the 60 ft IFR tolerance',
      'No. With QNH set it should read the 67 ft elevation, and any error over 30 ft makes it inoperative',
      'Yes. With QNH set it should read zero on the ground, so 17 ft is a small error',
      'No. With QNH set it should read 1013 hPa pressure altitude, so the reading cannot be checked',
    ], 0,
    `QNH is station pressure reduced to mean sea level, so an altimeter set to it reads the aerodrome elevation on the ground. For IFR, a system must read the site elevation within 60 ft; an error of 60 to 75 ft allows flight to the first landing for a recheck, and more than 75 ft makes the system inoperative. BoM aviation Area QNH guide, QNH; Part 91 MOS 2020 s 10.04.`,
    [bom('Area QNH guide, QNH'), mos91('10.04 checking pressure altitude systems, IFR')]),
  mcq('met.qnh.unit', ['met.qnh'], 'met',
    'A Sydney METAR ends Q1027. How should you set that on an altimeter with a hectopascal subscale, and how has the Bureau rounded it?', [
      'Set 1027 hPa; the observed value has been rounded down to the next whole hectopascal',
      'Set 10.27 inHg; the group is in hundredths of an inch',
      'Set 1027 hPa; the value has been rounded to the nearest whole hectopascal',
      'Set 1013 hPa; Q groups are only advisory and standard pressure is used below the transition altitude',
    ], 0,
    `Australian METAR QNH is in whole hectopascals, four figures after Q, and the observed value is rounded down to the next whole hectopascal, which keeps the altimeter reading on the safe side. ${METAR_GUIDE}, pressure (QNH).`,
    [bom('METAR/SPECI guide, pressure')], null, 1),

  // --- Flight planning: alternate ------------------------------------------------
  mcq('fp.alt.window', ['fp.alternate'], 'plan',
    'Your ETA at the destination is 14:00Z. The TAF forecasts relevant weather conditions from 14:20Z to 16:00Z. Must you nominate an alternate, and why?', [
      'Yes. An alternate is required if the ETA falls between 30 min before the conditions begin and 30 min after they end, so 13:50Z to 16:30Z captures 14:00Z',
      'No. The conditions begin after your ETA, so they do not affect your arrival',
      'No. Only conditions forecast at the exact ETA count',
      'Yes. Any relevant weather anywhere in the TAF validity requires an alternate',
    ], 0,
    `The pilot in command must nominate a destination alternate if the ETA is in the period that begins 30 minutes before the forecast commencement of relevant weather conditions and ends 30 minutes after their forecast ending. Part 91 MOS 2020 s 8.04 (1).`,
    [mos91('8.04 (1) destination alternate aerodromes, weather')], null, 1),
  mcq('fp.alt.minima', ['fp.alternate'], 'plan',
    'You are planning an IFR flight to an aerodrome where you can fly the ILS. Where do the alternate minima you must compare the TAF against come from?', [
      'The alternate minima published on the instrument approach chart for that procedure',
      'The landing minima on the chart, which double as alternate minima',
      'A fixed national value of 1 500 ft and 8 km',
      'The lowest safe altitude for the final route segment plus 500 ft, and 8 km',
    ], 0,
    `For IFR to an aerodrome with an instrument approach the pilot can conduct, the alternate minima are those published on the instrument approach chart. The LSALT-plus-500 ft and 8 km figure applies only by day to an aerodrome without a usable IAP, and 1 500 ft and 8 km is the VFR alternate minimum. Part 91 MOS 2020 s 8.08 (1), Table 8.08 (1).`,
    [mos91('8.08 Table 8.08 (1) alternate minima')]),
  mcq('fp.alt.prevailing', ['fp.alternate'], 'plan',
    'The prevailing forecast at your destination, FM061200 18028KT 4000 RA OVC008, is below the alternate minima and runs to 18:00Z. Your ETA is 15:00Z and you have 60 min of holding fuel. Does that holding fuel remove the need for an alternate?', [
      'No. Holding in lieu applies to INTER and TEMPO; for prevailing conditions you need fuel to hold until 30 min after they end, here 18:30Z, or an alternate',
      'Yes. Sixty minutes of holding fuel covers any deterioration in the forecast',
      'Yes. Thirty minutes would have been enough, because the conditions are prevailing rather than temporary',
      'No. Holding fuel can never substitute for an alternate',
    ], 0,
    `The 30 and 60 minute holding substitutes apply only when the relevant weather is forecast on an intermittent or temporary basis. For prevailing conditions, holding fuel removes the requirement only if it is enough to hold until the end of the period, which runs to 30 minutes after the forecast ending of the conditions. Part 91 MOS 2020 s 8.04 (5) and (6).`,
    [mos91('8.04 (5) and (6) holding in lieu of an alternate')]),
  mcq('fp.alt.notaf', ['fp.alternate'], 'plan',
    'You plan an IFR flight to a destination with an instrument approach, but no TAF and no ICAO landing forecast is available for it before departure. What does that do to your plan?', [
      'You must nominate a destination alternate, because the required forecast is not available',
      'You may use the latest METAR in place of the forecast and plan normally',
      'You may plan on CAVOK, since no forecast means no forecast deterioration',
      'You may depart and continue provided the GAF covers the area',
    ], 0,
    `For an IFR flight to a destination with an instrument approach the pilot can fly, the required forecast is an aerodrome forecast or ICAO landing forecast. If that forecast is not available, the pilot in command must nominate a destination alternate. Part 91 MOS 2020 s 7.02 (4) and 8.04 (3).`,
    [mos91('7.02 (4) forecasts for flight planning'), mos91('8.04 (3) forecast not available')]),
  mcq('fp.alt.cover', ['fp.alternate'], 'plan',
    'Your ETA is 23:30Z and the destination TAF is valid 0609/0700, ending at 00:00Z. Is this forecast enough for planning, and why?', [
      'No. The forecast must be valid from 30 min before to 60 min after the ETA, so it must extend to at least 00:30Z',
      'Yes. The TAF covers the ETA and 30 min after it, which is all the rule requires',
      'Yes. The last group of a TAF is assumed to continue until the next issue',
      'No. The TAF must cover the whole flight from departure to arrival',
    ], 0,
    `An authorised forecast used for the destination must be valid for at least 30 minutes before and 60 minutes after the planned ETA. A TAF ending at 00:00Z does not cover an ETA of 23:30Z, so the forecast is not available for planning and an alternate is required. Part 91 MOS 2020 s 7.02 (6) and 8.04 (3).`,
    [mos91('7.02 (6) forecast validity around the ETA')]),
  mcq('fp.alt.above', ['fp.alternate'], 'plan',
    'The destination TAF at your ETA ±30 min forecasts 9999 SCT030 with no TEMPO, INTER or PROB, and the alternate minima are 1 200 ft and 5 km. The forecast crosswind is within your aircraft limits. Does the weather require an alternate?', [
      'No. None of the relevant weather conditions is forecast, so no alternate is required on weather grounds',
      'Yes. Every IFR flight must carry an alternate regardless of the forecast',
      'Yes. SCT030 is cloud below the alternate ceiling once the 1 200 ft is added to it',
      'No, but 30 min of holding fuel is still mandatory',
    ], 0,
    `Relevant weather conditions are more than SCT below the alternate ceiling, visibility below the alternate minimum or a 30% or greater probability of a visibility-reducing phenomenon, a wind component beyond the aircraft limit, or a thunderstorm or 30% probability of one. None is present, so weather does not require an alternate; other grounds such as navigation aids or lighting are separate sections. Part 91 MOS 2020 s 8.02 (1), 8.04 (1).`,
    [mos91('8.02 (1) relevant weather conditions')]),
  mcq('fp.alt.ts', ['fp.alternate'], 'plan',
    'The destination TAF for your ETA is 9999 with FEW040CB, and an INTER group forecasts VRB20G30KT 4000 TSRA SCT100CB. Visibility and ceiling in the INTER are still above your alternate minima. Is an alternate or holding fuel required?', [
      'Yes. A thunderstorm is a relevant weather condition in its own right, so the INTER requires 30 min of holding fuel or an alternate',
      'No. The INTER stays above the alternate minima for cloud and visibility, which is all that is assessed',
      'No. CB on a TAF is only a turbulence advisory',
      'Yes, but only 60 min of holding will do, because thunderstorms are always treated as TEMPO',
    ], 0,
    `A thunderstorm, or its associated severe turbulence, is a relevant weather condition regardless of visibility and cloud. Forecast on an intermittent basis it is covered by 30 minutes of holding fuel or an alternate. Part 91 MOS 2020 s 8.02 (1) (d) and 8.04 (6).`,
    [mos91('8.02 (1) (d) thunderstorm as relevant weather')]),
  mcq('fp.alt.wind', ['fp.alternate'], 'plan',
    'The applicable maximum crosswind for your aircraft is 25 kt. The destination TAF forecasts 27030G40KT across the only runway at your ETA, with CAVOK. Does the wind affect the alternate decision?', [
      'Yes. A crosswind, headwind or downwind component beyond the aircraft maximum is a relevant weather condition, so an alternate or holding to the end of the period is needed',
      'No. The alternate decision is about cloud and visibility only, and the TAF is CAVOK',
      'No. Only the gust is above the limit, and gusts are ignored for planning',
      'Yes, but 60 min of holding fuel always covers a wind problem',
    ], 0,
    `Relevant weather conditions include a headwind, crosswind or downwind component more than the maximum for the aircraft. CAVOK does not remove the wind problem. Forecast as prevailing, it requires an alternate unless fuel is carried to hold until 30 minutes after it ends. Part 91 MOS 2020 s 8.02 (1) (c) and 8.04 (1), (5).`,
    [mos91('8.02 (1) (c) wind as relevant weather')]),
  mcq('fp.alt.vfr50', ['fp.alternate'], 'plan',
    'You are flying VFR by day to a destination 40 NM from your departure aerodrome, and the whole flight stays within 50 NM of the departure aerodrome. The destination TAF has a TEMPO below the VFR alternate minima at your ETA. Must you nominate an alternate?', [
      'No. The weather alternate requirement does not apply to a VFR flight by day that stays within 50 NM of the departure aerodrome',
      'Yes. Every TEMPO below minima requires 60 min of holding fuel or an alternate',
      'Yes. VFR flights must always nominate an alternate',
      'No. VFR flights are never subject to the alternate rules',
    ], 0,
    `The weather alternate requirements in s 8.04 (1) and (2) do not apply to a VFR flight by day within 50 NM of the departure aerodrome. Night VFR has its own navigation-based alternate rule. Part 91 MOS 2020 s 8.04 (4) and 8.05 (2).`,
    [mos91('8.04 (4) VFR by day within 50 NM')]),
  mcq('fp.alt.night-iap', ['fp.alternate'], 'plan',
    'You plan an IFR flight arriving at night at an aerodrome that has no instrument approach procedure. The TAF is CAVOK. Is an alternate required?', [
      'Yes. An IFR flight by night to a destination without an instrument approach the pilot can conduct must nominate an alternate, whatever the forecast',
      'No. CAVOK removes every alternate requirement',
      'No. The LSALT-plus-500 ft minima replace the alternate requirement at night',
      'Yes, but only if the aerodrome also lacks runway lighting',
    ], 0,
    `The weather test is only one of the alternate tests. An IFR flight by night to a planned destination not served by an instrument approach, or served only by approaches the pilot cannot conduct, must nominate a destination alternate regardless of the forecast. Part 91 MOS 2020 s 8.05 (1).`,
    [mos91('8.05 (1) destination alternate, navigation')]),
  mcq('fp.alt.lighting', ['fp.alternate'], 'plan',
    'Your night arrival is at an aerodrome with pilot-activated lighting and no responsible person on the ground. Besides a suitable alternate, what else would satisfy the lighting rule?', [
      'Fuel to hold at the destination until first light plus 10 minutes',
      'A second radio on board, which removes the requirement',
      'A NOTAM confirming the PAL system was serviced recently',
      'A TAF forecasting CAVOK for the arrival',
    ], 0,
    `A night landing at an aerodrome with PAL requires an alternate unless a qualified responsible person is in attendance to switch the lights on manually if PAL fails, or unless enough fuel is carried to hold until first light plus 10 minutes. A single-VHF aircraft may nominate a PAL aerodrome as its alternate only with a responsible person arranged to switch the lighting on manually, HF radio and 30 min of holding fuel. Part 91 MOS 2020 s 8.06 (3), (4) and (5).`,
    [mos91('8.06 destination alternate, aerodrome lighting')], null, 3),
  mcq('fp.alt.suitable', ['fp.alternate'], 'plan',
    'You want to nominate an aerodrome as your destination alternate, but its own TAF has a TEMPO below its alternate minima at the time you would arrive there. Can it be your alternate?', [
      'Only if you also carry 60 min of holding fuel for that TEMPO; without it, the aerodrome would itself require an alternate',
      'No. An aerodrome with any TEMPO below its alternate minima can never be nominated as an alternate',
      'Yes. Alternate aerodromes are not subject to weather requirements, so the TEMPO can be ignored',
      'No, because an alternate must always be forecast CAVOK at the time of use',
    ], 0,
    `An alternate must not itself be an aerodrome for which the aircraft would require an alternate. A TEMPO below the minima would require one, unless 60 minutes of holding fuel is carried for it, so the aerodrome is usable only with that fuel on board. Part 91 MOS 2020 s 8.07 (b) and 8.04 (6).`,
    [mos91('8.07 destination alternate, restrictions'), mos91('8.04 (6) holding for TEMPO and INTER')]),

  // --- Holding in lieu --------------------------------------------------------------
  mcq('fp.hold.tempo', ['fp.holding'], 'plan',
    'Planning under Part 91, at your ETA the prevailing forecast is above the alternate minima, but TEMPO 0612/0618 3000 SHRA BKN010 is below them. What are your options?', [
      'Nominate an alternate, or carry 60 min of holding fuel for the TEMPO',
      'Nominate an alternate, or carry 30 min of holding fuel for the TEMPO',
      'Carry final reserve fuel only, because TEMPO conditions are brief',
      'Nothing extra, because a TEMPO does not change the prevailing forecast',
    ], 0,
    `When relevant weather is forecast on a temporary basis, the alternate requirement does not apply if fuel is carried to hold for 60 minutes; for an intermittent (INTER) forecast it is 30 minutes. Final reserve fuel is a separate component and is not holding fuel. Part 91 MOS 2020 s 8.04 (6) (b) (ii).`,
    [mos91('8.04 (6) holding for TEMPO and INTER')]),
  mcq('fp.hold.inter', ['fp.holding'], 'plan',
    'Planning under Part 91, at your ETA the prevailing forecast is above the alternate minima, but INTER 0720/0800 3000 SHRA BKN010 is below them. How much holding fuel removes the need for an alternate?', [
      '30 minutes',
      '60 minutes',
      '15 minutes',
      'None, because INTER periods are too short to plan for',
    ], 0,
    `Relevant weather forecast on an intermittent basis is covered by fuel to hold for 30 minutes; on a temporary basis, 60 minutes. Part 91 MOS 2020 s 8.04 (6) (b) (i).`,
    [mos91('8.04 (6) holding for TEMPO and INTER')]),
  mcq('fp.hold.both', ['fp.holding'], 'plan',
    'Your destination TAF has both an INTER and a TEMPO below the alternate minima overlapping your ETA. If you plan holding fuel instead of an alternate, how much do you carry?', [
      '60 minutes, the most limiting requirement; the two are not added',
      '90 minutes, the sum of the two requirements',
      '30 minutes, because the INTER is the first group in the TAF',
      '45 minutes, the average of the two',
    ], 0,
    `When a forecast contains multiple INTER or TEMPO indicators, the holding fuel required is that for the most limiting requirement, so 60 minutes covers both. Part 91 MOS 2020 s 8.04 (7).`,
    [mos91('8.04 (7) multiple change indicators')]),
  mcq('fp.hold.short', ['fp.holding'], 'plan',
    'On a Part 91 flight, an INTER below the alternate minima overlaps your ETA. You have 20 min of holding fuel on the plan plus your final reserve. Is the INTER covered?', [
      'No. INTER needs 30 min of holding; final reserve cannot make up the shortfall, so add 10 min or nominate an alternate',
      'Yes. Twenty minutes is within the INTER definition of less than 30 minutes',
      'Yes. The final reserve of 30 min can be counted towards holding',
      'No, but 20 min is enough if the INTER starts after your ETA',
    ], 0,
    `The INTER substitute is 30 minutes of holding fuel. Final reserve fuel is the fuel that must still be on board after landing and is a separate component of the fuel requirement, so it cannot be used as holding fuel. Part 91 MOS 2020 s 8.04 (6) and 19.04 (1).`,
    [mos91('8.04 (6) holding for TEMPO and INTER'), mos91('19.04 (1) fuel components')]),
  mcq('fp.hold.onboard', ['fp.holding'], 'plan',
    'On a Part 91 flight you already carry 60 min of holding fuel for traffic delays into Sydney. The TAF then adds a TEMPO below the alternate minima at your ETA. Do you now need an alternate as well?', [
      'No. Sixty minutes of holding fuel satisfies the TEMPO requirement whatever the reason it was loaded',
      'Yes. Holding fuel for traffic cannot be counted against a weather TEMPO',
      'Yes. A TEMPO always requires an alternate as well as the holding fuel',
      'No, but you must now increase the holding to 120 min',
    ], 0,
    `The TEMPO alternate requirement does not apply if the pilot in command ensures sufficient fuel is carried to hold for 60 minutes. The rule looks at the fuel on board, not at why it was loaded, though the pilot still has to consider whether the traffic delay and the weather could coincide. Part 91 MOS 2020 s 8.04 (6).`,
    [mos91('8.04 (6) holding for TEMPO and INTER')]),

  // --- PROB ---------------------------------------------------------------------------
  mcq('fp.prob.30', ['fp.prob'], 'plan',
    'Your destination TAF at the ETA is 9999 NSC with PROB30 0618/0622 0500 FG. The prevailing visibility is above the alternate minimum. Does the PROB30 change your planning?', [
      'Yes. A 30% probability of fog below the alternate minimum is a relevant weather condition, so you need an alternate or fuel to hold until 30 min after the PROB period ends',
      'No. PROB30 is below the threshold that counts for planning; only PROB40 matters',
      'No. Fog is only assessed from the METAR on arrival',
      'Yes, but 30 min of holding fuel covers it, as for an INTER',
    ], 0,
    `Visibility at or above the alternate minimum with a forecast of at least a 30% probability of fog, mist, dust or any other phenomenon restricting visibility below the minimum is a relevant weather condition, so PROB30 counts as much as PROB40. A PROB without INTER or TEMPO is not a 30 or 60 minute holding case: hold until the end of the period or nominate an alternate. Part 91 MOS 2020 s 8.02 (1) (b) (ii) and 8.04 (5); BoM TAF guide, PROB.`,
    [mos91('8.02 (1) (b) (ii) probability of fog, mist, dust'), bom('TAF guide, PROB')]),
  mcq('fp.prob.40', ['fp.prob'], 'plan',
    'Your destination TAF contains PROB40 TEMPO 1102/1113 3000 TSRA BKN040CB across your ETA. Prevailing conditions are above the alternate minima. What must you plan?', [
      'An alternate, or 60 min of holding fuel: the probable thunderstorm counts, and TEMPO sets the holding period',
      'Nothing, because PROB groups are advisory',
      'An alternate only; holding fuel cannot cover a probability',
      '30 min of holding fuel, because TSRA is treated as INTER',
    ], 0,
    `A thunderstorm, or a forecast of at least a 30% probability of one, is a relevant weather condition. Forecast with TEMPO it is a temporary deterioration, so 60 minutes of holding fuel or an alternate satisfies the rule. Part 91 MOS 2020 s 8.02 (1) (d) and 8.04 (6).`,
    [mos91('8.02 (1) (d) thunderstorm as relevant weather'), mos91('8.04 (6) holding for TEMPO and INTER')]),
  mcq('fp.prob.taf3', ['fp.prob'], 'plan',
    'On a Part 121 flight your destination TAF3 is valid 0203/0303 with no service end time. It contains PROB30 0204/0206 0800 FG, and you will use the aerodrome from 04:30Z to 05:00Z. How does the TAF3 change the way you treat the PROB30?', [
      'It may be disregarded, because the PROB period and your time of use lie wholly within the first 3 hours of the TAF3',
      'It must still be treated exactly as on an ordinary TAF, because Part 121 has no TAF3 alleviation',
      'It may be disregarded only if your time of use falls within the first hour of the TAF3',
      'It becomes a prevailing forecast of fog, because a TAF3 PROB is firmer than a TAF PROB',
    ], 0,
    `Part 121 lets a PROB be disregarded on a TAF3 when the probability period is within the first 3 hours of validity and no part of the estimated time of use is after any TAF3 service end; here 04:00Z to 06:00Z lies inside 03:00Z to 06:00Z. AC 121-11 puts the test as the estimated time of use being wholly within those first 3 hours, which 04:30Z to 05:00Z also meets. Part 121 MOS 2020 s 4.06 (7); AC 121-11 para 3.4.11.1.`,
    [mos121('4.06 (7) TAF3 and probabilities'), { sourceId: 'casa-ac-121-11', section: '3.4.11.1 TAF3 PROB indicators' }], null, 3),

  // --- Fuel policy ------------------------------------------------------------------------
  mcq('fp.fuel.list', ['fp.fuel'], 'plan',
    'You are completing the fuel plan for a Part 121 flight to Sydney with a required alternate and a TEMPO in the destination TAF. Which amounts of usable fuel must be on board when the flight commences?', [
      'Taxi, trip, destination alternate, holding, contingency, final reserve and additional fuel',
      'Trip and final reserve fuel, with everything else at the operator\u2019s discretion',
      'Taxi, trip and a fixed 45 minute reserve',
      'Trip, alternate and holding fuel only; reserve is carried only on long sectors',
    ], 0,
    `At commencement a Part 121 aeroplane must carry at least taxi fuel, trip fuel to the destination, destination alternate fuel, holding fuel if required, contingency fuel, final reserve fuel, additional fuel if applicable, and any EDTO supplement. Part 91 lists the same components but conditionally: alternate and holding fuel if required, contingency and additional fuel if applicable, and contingency fuel does not apply to piston or turboprop aeroplanes of 5 700 kg MTOW or less. Part 121 MOS 2020 s 7.05 (1); Part 91 MOS 2020 s 19.04 (1) and Table 19.02 (2).`,
    [mos121('7.05 (1) fuel that must be carried'), mos91('19.04 (1) fuel components')], 4),
  mcq('fp.fuel.taxi', ['fp.fuel'], 'plan',
    'Your aeroplane burns 400 kg between engine start and take-off at a busy aerodrome with APU running. Where does that fuel sit in the plan?', [
      'As taxi fuel, a separate component covering burn before take-off including the APU and local conditions',
      'Inside trip fuel, which starts at engine start',
      'Inside contingency fuel, which exists for ground delays',
      'Inside final reserve fuel, because it is the first fuel used',
    ], 0,
    `Taxi fuel is the fuel expected to be used before take-off, taking into account local conditions at the departure aerodrome and APU consumption. Trip fuel begins with take-off and climb. Part 121 MOS 2020 s 1.04, taxi fuel and trip fuel.`,
    [mos121('1.04 definitions, taxi fuel')]),
  mcq('fp.fuel.trip', ['fp.fuel'], 'plan',
    'Which segments of the flight does trip fuel have to cover?', [
      'Take-off and climb, cruise including step climbs, descent to the approach, and the approach and landing at the destination',
      'Engine start to shutdown, including taxi at both ends',
      'Cruise only; climb and descent are covered by contingency fuel',
      'The flight to the alternate, since the destination may be closed',
    ], 0,
    `Trip fuel is the fuel to fly from take-off until landing at the aerodrome: take-off and climb to initial cruising level allowing for the departure routing, cruise from top of climb to top of descent including step climbs and descents, descent to the approach, and the approach and landing. Part 121 MOS 2020 s 1.04, trip fuel.`,
    [mos121('1.04 definitions, trip fuel')]),
  mcq('fp.fuel.extra', ['fp.fuel'], 'plan',
    'The dispatcher\u2019s plan meets every required fuel component, including holding fuel for the delay ATC expects. With nothing further forecast, you choose to load another 600 kg as a margin. What is that fuel, and who decides it?', [
      'Discretionary fuel, carried at the pilot in command\u2019s discretion on top of the required components',
      'Contingency fuel, which the pilot sets at any percentage of trip fuel',
      'Additional fuel, which the operator sets for an engine failure en route',
      'Final reserve fuel, which the pilot may increase for weather',
    ], 0,
    `Discretionary fuel is an extra amount carried at the discretion of the pilot in command, beyond the required components. Fuel for holding that is anticipated, such as an expected ATC delay, is not discretionary: it is holding fuel, a required component. AC 91-15 para 1.2, discretionary fuel; Part 121 MOS 2020 s 1.04, holding fuel.`,
    [{ sourceId: 'casa-ac-91-15', section: '1.2 definitions, discretionary fuel' }, mos121('1.04 definitions, holding fuel')]),
  mcq('fp.fuel.additional', ['fp.fuel'], 'plan',
    'Over a remote sector, an engine failure or depressurisation at the critical point would leave the aeroplane short of fuel to reach a suitable aerodrome. Which fuel component covers that case?', [
      'Additional fuel: enough to divert from the critical point, hold 15 minutes at 1 500 ft, and approach and land',
      'Contingency fuel: the 5% of trip fuel covers all failure cases',
      'Destination alternate fuel: the alternate is the diversion aerodrome',
      'Final reserve fuel: it exists for emergencies',
    ], 0,
    `Additional fuel is the supplementary amount required so that, after an engine failure or loss of pressurisation at the most critical point along the route (whichever burns more), the aeroplane can proceed to an alternate aerodrome, fly for 15 minutes at holding speed at 1 500 ft above the aerodrome in ISA, and make an approach and landing. Part 121 MOS 2020 s 1.04, additional fuel.`,
    [mos121('1.04 definitions, additional fuel')]),

  // --- Final reserve ---------------------------------------------------------------------------
  mcq('fp.res.30', ['fp.reserve'], 'plan',
    'How much final reserve fuel must a turbine-engine aeroplane carry under Part 121, and what is it for?', [
      '30 minutes of holding fuel, which must still be usable on completion of the final landing',
      '45 minutes of holding fuel, usable for the approach if needed',
      '60 minutes of cruise fuel, to reach a second alternate',
      '5% of trip fuel, as a buffer against headwinds',
    ], 0,
    `Final reserve fuel for a turbine-engine aeroplane is the fuel to fly for 30 minutes at holding speed at 1 500 ft above aerodrome elevation in ISA, at the estimated weight on arrival at the alternate or destination; for a piston-engine aeroplane it is 45 minutes. It is the usable fuel remaining after the final landing, not fuel to be planned into the flight. Part 121 MOS 2020 s 1.04, final reserve fuel; Part 91 MOS 2020 Table 19.02 (2).`,
    [mos121('1.04 definitions, final reserve fuel'), mos91('19.02 Table 19.02 (2) final reserve')]),
  mcq('fp.res.height', ['fp.reserve'], 'plan',
    'At what conditions is the 30 minute turbine final reserve calculated?', [
      'Holding speed, 1 500 ft above aerodrome elevation, ISA, at the estimated landing weight at the alternate or destination',
      'Long-range cruise at the planned cruising level, at take-off weight',
      'Holding speed at sea level, standard day, at maximum landing weight',
      'Best endurance speed at 10 000 ft, at the planned landing weight',
    ], 0,
    `Final reserve fuel is calculated for the period in the table (30 minutes turbine, 45 minutes piston) at 1 500 ft above aerodrome elevation in ISA conditions, at holding speed, at the aeroplane\u2019s estimated weight on arrival at the destination alternate, or at the destination if no alternate is required. Part 121 MOS 2020 s 1.04, final reserve fuel.`,
    [mos121('1.04 definitions, final reserve fuel')]),
  mcq('fp.res.727', ['fp.reserve'], 'plan',
    'The ATPL flight planning exam uses the Boeing 727-200. Which final reserve rule applies to it, and where does the fuel flow figure come from?', [
      'The turbine rule of 30 minutes holding; the burn comes from the aeroplane\u2019s performance data, not from the rule',
      'The piston rule of 45 minutes, because the 727 is a three-engine aeroplane',
      'A 727-specific 15 minute reserve set out in the CASA handbook',
      'Whatever reserve the destination METAR wind allows',
    ], 0,
    `A turbine-engine aeroplane carries 30 minutes of final reserve at holding speed at 1 500 ft; the regulation sets the time and conditions and the aeroplane\u2019s performance data (here the CASA B727 handbook) supplies the fuel flow. Part 121 MOS 2020 s 1.04 and 7.04 (1); Boeing 727 Performance and Operating Handbook.`,
    [mos121('1.04 definitions, final reserve fuel'), book727('Holding fuel flow')]),
  mcq('fp.res.protect', ['fp.reserve'], 'plan',
    'Approaching Sydney you are told to expect 25 minutes of holding. Working the numbers, any further delay would mean landing with less than final reserve, though you are committed to Sydney. What must you declare?', [
      'MINIMUM FUEL, because any change to the clearance would mean landing below final reserve; it is not yet an emergency',
      'MAYDAY FUEL, because holding is already eating into the final reserve',
      'Nothing yet, because final reserve is there to be used for holding',
      'PAN PAN, requesting priority over other traffic',
    ], 0,
    `A pilot committed to an aerodrome who determines that any change to the existing clearance would result in landing with less than final reserve must declare MINIMUM FUEL. It tells ATS the options have reduced to one aerodrome and is not a request for priority. If the fuel on landing at the nearest suitable aerodrome will be below final reserve, the pilot must declare MAYDAY MAYDAY MAYDAY FUEL. Part 91 MOS 2020 s 19.06 (3) and (4).`,
    [mos91('19.06 (3) and (4) minimum fuel and emergency fuel')]),

  // --- Contingency and alternate fuel -------------------------------------------------------
  mcq('fp.con.5', ['fp.contingency'], 'plan',
    'Trip fuel for your turbine aeroplane is 6 000 kg and five minutes at holding speed at 1 500 ft burns 350 kg. What is the minimum contingency fuel?', [
      '350 kg, because contingency is the greater of 5% of trip fuel (300 kg) and 5 minutes of holding',
      '300 kg, because contingency is 5% of trip fuel and nothing more',
      '600 kg, because contingency for a turbine aeroplane is 10% of trip fuel',
      '650 kg, because 5% of trip fuel and 5 minutes of holding are added together',
    ], 0,
    `Contingency fuel compensates for unforeseen factors and must be at least 5% of trip fuel for a turbine aeroplane (10% for piston), and not less than the fuel to fly for 5 minutes at holding speed at 1 500 ft above the destination in ISA. Here 5 minutes (350 kg) exceeds 5% (300 kg). Part 121 MOS 2020 s 7.03 (2).`,
    [mos121('7.03 (2) contingency fuel')]),
  mcq('fp.con.alt', ['fp.contingency'], 'plan',
    'A destination alternate is required. What flight does destination alternate fuel have to cover?', [
      'A missed approach at the destination, climb to cruise, the routing to the alternate, descent, the approach and the landing there',
      'Cruise from the destination to the alternate only; the missed approach is in trip fuel',
      'The flight to the alternate plus 30 minutes of final reserve',
      'Fifteen minutes of holding at the destination',
    ], 0,
    `Destination alternate fuel is the fuel to perform a missed approach at the destination, climb to the expected cruising altitude, fly the expected routing to the alternate, descend to the approach, conduct the approach and land. Final reserve remains a separate component. Part 121 MOS 2020 s 7.02 (1).`,
    [mos121('7.02 (1) destination alternate fuel')]),
  mcq('fp.con.none', ['fp.contingency'], 'plan',
    'Under Part 121 the weather and other conditions at your destination mean no alternate is required and the destination is not isolated. What becomes of the destination alternate fuel component?', [
      'It becomes 15 minutes at holding speed at 1 500 ft above the destination in ISA',
      'It becomes zero, because there is no alternate to fly to',
      'It stays at the fuel to the nearest suitable aerodrome',
      'It is replaced by doubling the final reserve to 60 minutes',
    ], 0,
    `When a Part 121 aeroplane operates without a destination alternate, other than to an isolated aerodrome, the destination alternate fuel is the fuel to fly for 15 minutes at holding speed at 1 500 ft above the destination elevation in ISA. Contingency and final reserve are unchanged. Part 121 MOS 2020 s 7.02 (3).`,
    [mos121('7.02 (3) no destination alternate')]),
  mcq('fp.con.isolated', ['fp.contingency'], 'plan',
    'Your turbine aeroplane is planned to an isolated destination aerodrome with no alternate. What destination alternate fuel must you carry?', [
      'Fuel to fly for 2 hours at normal cruise consumption above the aerodrome, including final reserve',
      'Fifteen minutes at holding speed at 1 500 ft',
      'Forty-five minutes plus 15% of the planned cruise time',
      'None, because an isolated aerodrome is exempt from alternate fuel',
    ], 0,
    `For a turbine-engine aeroplane operated to an isolated destination without an alternate, the destination alternate fuel is the fuel to fly for 2 hours at normal cruise consumption above the aerodrome, including final reserve. The 45 minutes plus 15% of cruise time, capped at 2 hours, is the piston-engine figure. Part 121 MOS 2020 s 7.02 (4).`,
    [mos121('7.02 (4) isolated destination aerodrome')], null, 3),
  mcq('fp.con.replan', ['fp.contingency'], 'plan',
    'During cruise you burn fuel to deviate 60 NM around weather. What does that oblige you to do with the fuel plan?', [
      'Re-analyse the planned use of fuel for the rest of the flight and adjust the flight so the remaining requirements are still met',
      'Nothing, because contingency fuel exists for exactly this and absorbs the burn automatically',
      'Declare MINIMUM FUEL immediately as a precaution',
      'Reduce the final reserve by the amount used for the deviation',
    ], 0,
    `If, after commencement, fuel is used for a purpose other than that intended in pre-flight planning, the pilot in command must re-analyse the planned use of fuel for the remainder of the flight and adjust the flight as necessary to remain within the fuel requirements; the aeroplane must still land with final reserve intact. Part 121 MOS 2020 s 7.05 (4); Part 91 MOS 2020 s 19.04 (4).`,
    [mos121('7.05 (4) fuel used for another purpose'), mos91('19.04 (4) fuel used for another purpose')]),
];

export const laterCard: Card = {
  id: 'fp.b727.later',
  conceptIds: ['fp.later'],
  subject: 'plan',
  kind: 'later',
  planStep: 5,
  stem: 'B727-200 performance',
  options: [],
  correctId: '',
  explanation: 'Take-off, climb, cruise and landing numbers from the CASA Boeing 727 Performance and Operating Handbook come later.',
  citations: [book727('Performance and Operating Handbook — not digitised')],
  complexity: 3,
  topics: ['727'],
};

export const fuelPlanCardId = 'fp.fuel.list';

export function library(snapshot: Snapshot | null): Card[] {
  return [...staticCards, laterCard, ...liveCards(snapshot)];
}
