/** Original level cards. Curious and Drone cover the graph; pilot cards are the
 * verified rule variants; Defence leads with a picture. Not an exam bank. */

import type { LearnLevel, LearnRules, Strand } from './levels.ts';

export interface Seed {
  concept: string;
  level: LearnLevel;
  rules: LearnRules | 'both' | null;
  claim: 'rule' | 'mechanism';
  strands: Strand[];
  stem: string;
  options: [string, string, string, string];
  explanation: string;
  sourceId: string;
  section: string;
  picture: string;
  caption: string;
}

const pic = {
  low: ['isobars', 'Lines curling into a low'] as const,
  tight: ['isobars', 'Isobars packed on the map'] as const,
  spin: ['isobars', 'Wind bending along the lines'] as const,
  wind: ['wind', 'Wind strengthening near the ground'] as const,
  cloud: ['cloud', 'Cloud base over the place'] as const,
  rain: ['rain', 'A rain band crossing the map'] as const,
  storm: ['storm', 'A storm tower on the map'] as const,
  ice: ['ice', 'Ice on a cold airframe'] as const,
  fog: ['fog', 'A shallow fog layer'] as const,
  temp: ['temp', 'Warm air over the place'] as const,
  moon: ['moon', 'Moonrise over the place'] as const,
  soil: ['soil', 'Rain, then soft ground'] as const,
  sea: ['sea', 'Sea state under a tight gradient'] as const,
  drift: ['drift', 'A parachute drifting off its line'] as const,
  thermal: ['thermal', 'Warm and cool surfaces crossing'] as const,
  hazard: ['hazard', 'A plume leaving downwind'] as const,
  alt: ['alt', 'Thin air over high ground'] as const,
  map: ['map', 'Today’s chart at this place'] as const,
};

function row(
  concept: string,
  level: LearnLevel,
  rules: Seed['rules'],
  claim: Seed['claim'],
  strands: Strand[],
  stem: string,
  options: [string, string, string, string],
  explanation: string,
  sourceId: string,
  section: string,
  scene: readonly [string, string],
): Seed {
  return {
    concept, level, rules, claim, strands, stem, options, explanation, sourceId, section,
    picture: scene[0], caption: scene[1],
  };
}

const M = 'bom-mam';
const B = 'bom-aviation';
const W = 'faa-wx';
const physics: Strand[] = ['physics'];
const charts: Strand[] = ['charts'];
const ops: Strand[] = ['operations'];
const numbers: Strand[] = ['numbers'];

/** Plain-language cards. The picture is the lesson; the question asks what happens next. */
export const curiousSeeds: Seed[] = [
  row('met.pressure-systems', 'curious', null, 'mechanism', physics,
    'You are watching the lines on today’s map curl into a low just west of you. What happens under that low next?',
    ['The air rises and cloud thickens under the low', 'The air sinks and the sky clears under the low', 'The lines there mean the wind has stopped', 'The low on the map is only a temperature mark'],
    'Air rises in a low, so cloud and rain favour that part of the map. The lines are pressure.',
    M, 'Pressure systems', pic.low),
  row('met.pressure-gradient', 'curious', null, 'mechanism', physics,
    'The lines on the map are packed tightly just west of your place. What happens to the wind there next?',
    ['The wind there gets stronger as the lines pack in', 'The wind there fades because packed lines are calm', 'Rain starts there because tight lines are a cloud', 'The temperature jumps because the lines are a front'],
    'Packed lines are a strong pressure change, and that drives a stronger wind.',
    M, 'Pressure gradient', pic.tight),
  row('met.coriolis', 'curious', null, 'mechanism', physics,
    'You are south of the equator, watching air try to flow straight from high pressure toward low. What happens to that air next?',
    ['The moving air is bent until it follows the lines', 'The moving air ignores the Earth and stays straight', 'The bend reverses because the map is upside down', 'The air stops as soon as it leaves the high'],
    'The Earth turns under moving air, so the flow bends and ends up along the lines rather than across them.',
    M, 'Coriolis', pic.spin),
  row('met.geostrophic', 'curious', null, 'mechanism', physics,
    'Above the ground, the push of the pressure lines and the Earth’s turn are in balance. Which way does that wind go?',
    ['Along the lines, with the low on the right here', 'Straight across the lines, into the low', 'Along the lines, with the low on the left here', 'In a circle that ignores the lines entirely'],
    'In balance the wind follows the lines. South of the equator the low stays on the right of the wind.',
    M, 'Geostrophic wind', pic.spin),
  row('met.gradient-wind', 'curious', null, 'mechanism', physics,
    'The lines around a low on the map are curved, not straight. What does that curve do to the wind next?',
    ['The curve slows the wind around the low', 'The curve speeds the wind around the low', 'The curve only changes the temperature', 'The curve erases the pressure difference'],
    'Air going around a low is held outward by its curve, so the wind is a little slower than the straight-line balance.',
    M, 'Gradient wind', pic.spin),
  row('met.surface-friction', 'curious', null, 'mechanism', physics,
    'The wind up above follows the lines, then it meets the ground. What happens to that wind next?',
    ['It slows and leaks across the lines toward the low', 'It speeds up and follows the lines more tightly', 'It stops, because the ground cancels pressure', 'It turns back until it blows into the high'],
    'Friction slows the wind and lets it cross the lines toward lower pressure.',
    M, 'Surface friction', pic.wind),
  row('met.buys-ballot', 'curious', null, 'mechanism', physics,
    'You stand with the surface wind on your back in Australia and look along it. Where is the low?',
    ['The low is on your right in this hemisphere', 'The low is on your left in this hemisphere', 'The low is straight ahead, where you look', 'The low is always behind you, upwind'],
    'South of the equator, wind at your back puts the low on your right. A northern-hemisphere diagram swaps that.',
    M, 'Buys Ballot', pic.wind),
  row('met.temperature', 'curious', null, 'mechanism', physics,
    'You watch the temperature colour over your place through the afternoon. What happens to rising air next?',
    ['Rising air cools as it expands on the way up', 'Rising air warms because height adds heat', 'The colour is rain, so temperature stays fixed', 'Air only cools when a front is drawn on it'],
    'A parcel that rises expands and cools. That is why cloud can form as air goes up.',
    M, 'Temperature and lapse rate', pic.temp),
  row('met.moisture', 'curious', null, 'mechanism', physics,
    'The temperature and the dewpoint on the map are almost the same at your place. What happens next?',
    ['The air is near saturation and cloud is easy', 'The air is dry and cloud becomes unlikely', 'The dewpoint is a wind speed, not moisture', 'Equal numbers mean the pressure is falling'],
    'A small temperature–dewpoint gap means the air is close to saturation, so cloud or fog is easier.',
    M, 'Moisture', pic.cloud),
  row('met.stability', 'curious', null, 'mechanism', physics,
    'A bubble of air near the ground is warmer than the air around it. What happens to that bubble next?',
    ['It keeps rising while it stays warmer', 'It sinks because warm air is heavier', 'It stays put because warmth is not lift', 'It only rises if a chart draws a front'],
    'Warmer air is less dense, so the bubble rises until it matches its surroundings. That is instability.',
    M, 'Stability', pic.storm),
  row('met.thunderstorm', 'curious', null, 'mechanism', physics,
    'The map shows lift, moisture and unstable air stacked over one place. What happens there next?',
    ['A storm can build if all three stay together', 'A storm needs only a red line on the chart', 'The three together guarantee a clear sky', 'Storms form only when the lines are far apart'],
    'A thunderstorm wants lift, moisture and instability together. Missing one of them and the tower does not grow.',
    M, 'Thunderstorms', pic.storm),
  row('met.ceiling', 'curious', null, 'mechanism', charts,
    'You read a cloud report of a few wisps and a broken layer lower down. Which one is the ceiling?',
    ['The broken layer, because it covers half the sky', 'The wisps, because they are named first', 'Neither, because only rain is a ceiling', 'Both, added together into one height'],
    'A ceiling is the lowest broken or overcast layer. A few wisps do not cover enough sky to be one.',
    B, 'METAR guide, cloud', pic.cloud),
  row('met.taf-groups', 'curious', null, 'mechanism', charts,
    'A forecast says the weather will change for a short spell and then go back. What happens in that spell?',
    ['The change is temporary and the old weather returns', 'The change is permanent for the rest of the day', 'The spell can be ignored because it is short', 'The spell is a second aerodrome, not weather'],
    'A temporary group is a spell of different weather, then a return. It is not the new normal.',
    B, 'TAF guide, TEMPO', pic.map),
  row('met.icing', 'curious', null, 'mechanism', physics,
    'Cloud drops are still liquid below freezing and an aircraft flies through them. What happens on the wing next?',
    ['The drops freeze onto the wing as ice', 'The drops stay liquid and fall away harmlessly', 'Ice forms only in cloud that is already snow', 'The wing warms the drops so they evaporate'],
    'Supercooled drops freeze on contact with a wing that is at or below freezing.',
    M, 'Icing', pic.ice),
  row('met.turbulence', 'curious', null, 'mechanism', physics,
    'The wind above your place changes speed sharply over a short height. What does an aircraft feel there?',
    ['Bumps, because the layers are sliding past', 'Smooth air, because a change of speed is calm', 'Only a heading change, with no bump', 'Rain, because shear is a cloud type'],
    'Wind shear between layers shakes an aircraft. The bump is the shear, not a separate object on the map.',
    M, 'Turbulence', pic.wind),
  row('met.fronts', 'curious', null, 'mechanism', physics,
    'A colder air mass is advancing into warmer air on the map. What happens at the boundary next?',
    ['The warm air is lifted and cloud forms there', 'The two air masses mix with no cloud at all', 'The boundary is only a line of equal pressure', 'The cold air rises and the warm air sinks'],
    'The colder air undercuts the warmer air, so the warm air rises and cloud forms along the boundary.',
    M, 'Fronts', pic.rain),
  row('nav.place-time', 'curious', null, 'mechanism', charts,
    'A forecast time is written in UTC and you live in a different clock. What do you do with that time?',
    ['Convert it into the local clock of the place', 'Read the UTC digits as if they were local', 'Add a day, because UTC is always tomorrow', 'Ignore the time and use sunrise instead'],
    'The forecast clock is UTC. The useful clock is the place’s own, which you convert. Perth does not do daylight saving; Sydney does.',
    M, 'Time', pic.map),
  row('nav.great-circle', 'curious', null, 'mechanism', numbers,
    'You draw the shortest path between two far places on the Earth. What does that path do?',
    ['It is a great circle, the short arc of a hoop', 'It is a straight line on every flat map', 'It follows a line of latitude the whole way', 'It is longer than any other route you draw'],
    'The shortest path on a sphere is a great circle. A straight line on a flat map is usually not that path.',
    M, 'Great circle', pic.map),
  row('fpl.wind-component', 'curious', null, 'mechanism', numbers,
    'The wind is blowing across a runway rather than straight down it. What does that wind do to an aircraft?',
    ['Part of it pushes sideways as a crosswind', 'All of it becomes a headwind on the nose', 'None of it matters once the wheels are down', 'It only changes the temperature on approach'],
    'A wind at an angle splits into a headwind or tailwind along the runway and a crosswind across it.',
    M, 'Wind components', pic.wind),
  row('fpl.taf-threshold', 'curious', null, 'mechanism', charts,
    'One line of a forecast is much cloudier than the line before it. What are you comparing?',
    ['Which line first becomes the worse weather', 'Which line was typed at the top of the page', 'Which aerodrome is alphabetically first', 'Which line has the most numbers in it'],
    'You compare the weather each line describes, and notice the first line that crosses into the worse conditions.',
    B, 'TAF guide, change groups', pic.cloud),
  row('fpl.track-correction', 'curious', null, 'mechanism', numbers,
    'You point an aircraft at a place but the wind is from the side. Where does the aircraft go next?',
    ['It drifts downwind unless you aim upwind', 'It stays on the line you pointed, wind or not', 'It turns into the wind and stops moving', 'The drift is only a change in its height'],
    'A side wind carries the aircraft off the line you pointed. You aim into the wind to cancel that drift.',
    M, 'Drift', pic.drift),
  row('fpl.cruise-level', 'curious', null, 'mechanism', numbers,
    'Two aircraft are crossing the same area at the same height. What keeps them apart by direction?',
    ['Each direction of travel has its own height band', 'They share one height and rely on luck', 'The higher aircraft is always the faster one', 'Height is chosen only by how warm it is'],
    'Cruising heights are organised by the direction you are going, so opposite traffic is not at the same level.',
    M, 'Cruising levels', pic.alt),
  row('fpl.safe-return', 'curious', null, 'mechanism', numbers,
    'You have enough fuel to go on, or to turn back, and the two choices are equal. What point is that?',
    ['The last point where turning back still works', 'The point where the destination is in sight', 'The point where the tanks are already empty', 'A point that only exists on a tailwind day'],
    'The point of safe return is where the fuel to continue and the fuel to go back are equal. Past it, back costs more.',
    M, 'Point of safe return', pic.map),
  row('perf.pressure-altitude', 'curious', null, 'mechanism', numbers,
    'The pressure at your place is lower than the usual sea-level pressure. What does the air column think?',
    ['You are higher than the ground elevation alone', 'You are lower, because low pressure is dense', 'Pressure does not change how high the air feels', 'The altimeter ignores pressure and shows zero'],
    'Low pressure is what you would meet higher up in the standard air, so the pressure altitude is above the ground.',
    M, 'Pressure altitude', pic.alt),
  row('perf.density-altitude', 'curious', null, 'mechanism', physics,
    'It is a hot day at a high place. What happens to the air an aircraft has to use?',
    ['The air is thinner, as if the place were higher', 'The air is thicker because heat packs it in', 'Heat changes the wind but not the air’s density', 'Height and heat cancel, so nothing changes'],
    'Hot air and high elevation both thin the air. The aircraft performs as if it were at a higher place.',
    M, 'Density altitude', pic.alt),
  row('perf.takeoff-factors', 'curious', null, 'mechanism', ops,
    'An aircraft starts its takeoff on a hot day with a tailwind. What happens to the ground roll next?',
    ['The ground roll gets longer than on a cool morning', 'The ground roll gets shorter because the heat helps', 'The tailwind holds the aircraft straight on the line', 'Only the weight of the fuel changes that distance'],
    'Thin air and a tailwind both mean the wing needs more distance before it can lift the aircraft.',
    M, 'Takeoff', pic.alt),
  row('perf.weight', 'curious', null, 'mechanism', numbers,
    'You load an aircraft so its weight sits further back than usual. What changes in the way it flies?',
    ['It becomes less stable and easier to pitch', 'It becomes heavier on the nose and slower', 'The balance does not change the way it flies', 'Aft weight only matters to the paint scheme'],
    'An aft load reduces the nose’s tendency to drop back to the trimmed attitude, so stability falls.',
    M, 'Weight and balance', pic.map),
  row('aero.lift', 'curious', null, 'mechanism', physics,
    'A wing is moving through thinner air than it was a minute ago. What does the wing need next to hold the same lift?',
    ['More speed or a greater angle to the air', 'Less speed, because thin air lifts more', 'Nothing, because lift ignores the air’s density', 'A steeper descent so the wing unloads'],
    'Lift depends on the density of the air, the speed, and the angle. Thinner air means you need more of the other two.',
    M, 'Lift', pic.wind),
  row('aero.induced-drag', 'curious', null, 'mechanism', physics,
    'An aircraft is flying slowly with its nose well up. What is happening to the drag from the wing?',
    ['That drag rises as the wing works harder', 'That drag falls because slow flight is efficient', 'Drag of this kind only appears in a dive', 'The nose-up attitude removes drag entirely'],
    'The drag that comes from making lift gets worse as you fly slower. On that side of the curve, raising the nose without power makes you sink faster.',
    M, 'Induced drag', pic.alt),
  row('aero.stall-aoa', 'curious', null, 'mechanism', physics,
    'A wing reaches the steepest angle to the air it can hold. What happens next, whatever the speed dial says?',
    ['The wing stalls because of that angle', 'The wing stalls only below one fixed speed', 'The wing cannot stall if the nose is down', 'The dial, not the angle, decides the stall'],
    'A stall is an angle of attack. The speed at which you reach that angle changes with weight, but the angle does not.',
    M, 'Stall', pic.wind),
  row('aero.load-factor', 'curious', null, 'mechanism', physics,
    'You watch an aircraft in a steep level turn. What happens to the load on the wing?',
    ['The wing carries more than the aircraft’s weight', 'The wing carries less because the turn is banked', 'The load stays equal to the weight in any turn', 'A level turn unloads the wing completely'],
    'In a level turn the wing must lift more than the weight. A 60 degree bank is about twice the weight.',
    M, 'Load factor', pic.spin),
  row('aero.manoeuvre-speed', 'curious', null, 'mechanism', physics,
    'A sharp gust hits a wing that is flying at or below its manoeuvre speed. What is the wing designed to do?',
    ['Stall before the gust breaks the structure', 'Hold any gust with no change in load', 'Speed up so the gust cannot reach it', 'Ignore the gust because speed is a limit'],
    'At or below manoeuvre speed the wing should stall before it reaches its breaking load. That speed falls when the aircraft is lighter.',
    M, 'Manoeuvre speed', pic.wind),
  row('sys.pitot-static', 'curious', null, 'mechanism', physics,
    'The tube that senses the rush of air is blocked, and the vents that sense still air are not. What does the speed dial do as you climb?',
    ['It reads too high as you climb away', 'It falls to zero and stays there', 'It is unaffected because it uses satellites', 'It shows the true wind over the ground'],
    'A blocked pitot traps the old pressure. Climbing lowers the still-air pressure around it, so the dial shows a higher speed than you have.',
    M, 'Pitot-static', pic.alt),
  row('sys.anti-ice', 'curious', null, 'mechanism', physics,
    'You are in cloud and the outside air is below freezing. Where can ice form on the aircraft?',
    ['On the airframe, from liquid drops in the cloud', 'Only on the ground, after you have landed', 'Only inside the cabin, on the windows', 'Nowhere, because cloud drops cannot freeze'],
    'Liquid drops in cloud below freezing freeze onto a cold airframe. That is why ice is a cloud problem, not only a snow problem.',
    M, 'Airframe ice', pic.ice),
  row('sys.pressurisation', 'curious', null, 'mechanism', physics,
    'An aircraft climbs and the air outside becomes too thin to breathe comfortably. What is the cabin doing?',
    ['It holds a thicker air than the sky outside', 'It copies the outside air with no difference', 'It adds oxygen until the mix is no longer air', 'It only matters for the altimeter, not people'],
    'The cabin is held at a lower, thicker altitude than the aircraft’s real height, so the people inside still have enough air.',
    M, 'Pressurisation', pic.alt),
  row('hum.hypoxia', 'curious', null, 'mechanism', physics,
    'You climb until the air is thin, and the oxygen is still about a fifth of the mix. What happens to you next?',
    ['Each breath brings less oxygen than at sea level', 'The mix becomes pure oxygen as you climb', 'Nothing, because the fraction of oxygen is fixed', 'You notice immediately and cannot be surprised'],
    'The fraction stays near 21 percent, but the pressure of that oxygen falls, so each breath delivers less. Judgement can fade before you feel it.',
    M, 'Hypoxia', pic.alt),
  row('hum.vestibular', 'curious', null, 'mechanism', physics,
    'You are in cloud, you cannot see the horizon, and your inner ear says the wings are level. What should you trust?',
    ['The instruments, because the ear can be wrong', 'The ear, because it feels the real horizon', 'The seat, because pressure is an attitude', 'Neither, and wait until the cloud ends'],
    'Without a visual horizon the inner ear misleads. The instruments are the horizon you still have.',
    M, 'Vestibular illusions', pic.cloud),
  row('hum.fatigue-rules', 'curious', null, 'mechanism', ops,
    'You have been awake too long and the chart is still in front of you. What happens to your reading of it?',
    ['You miss things you would have caught when fresh', 'Fatigue sharpens the way you read a chart', 'Sleep only matters after the flight is over', 'A tired reader is safer because they go slower'],
    'Fatigue narrows attention. The legal limits on duty are a separate rule; the effect on your reading starts earlier.',
    M, 'Fatigue', pic.map),
  row('law.transition-altitude', 'curious', null, 'mechanism', physics,
    'You climb until the altimeter stops using the local pressure and uses one standard setting. Why do countries do that?',
    ['So everyone high up is on the same pressure', 'So the dial can show the temperature instead', 'So low flying can ignore the local pressure', 'So the map’s lines become the height itself'],
    'Above a published height everyone sets the same standard pressure, so vertical separation does not depend on each aerodrome’s setting.',
    M, 'Altimetry', pic.alt),
  row('law.alternate', 'curious', null, 'mechanism', charts,
    'The forecast at the place you want to land looks as if it may be too poor when you arrive. What is the idea of an alternate?',
    ['A second place you can reach if the first is poor', 'A second copy of the same forecast, filed twice', 'A note that lets you ignore the poor forecast', 'A higher cruise level that removes the weather'],
    'An alternate is another aerodrome you plan to reach if the destination’s weather is not good enough to land.',
    M, 'Alternates', pic.cloud),
  row('law.documents', 'curious', null, 'mechanism', ops,
    'Someone asks which paper says a pilot may fly a certain aircraft. What are they really asking?',
    ['Which published rule gives that permission', 'Which map colour means the flight is allowed', 'Which wind speed replaces a licence', 'Which forecast line is the permission itself'],
    'Permission to fly sits in the country’s aviation rules, not in the weather map. The map tells you the air, not the licence.',
    M, 'Licensing', pic.map),
  row('drone.low-level-wind', 'curious', null, 'mechanism', physics,
    'You are watching gusts ruffle the trees at the place on the map. What is a gust, in plain words?',
    ['A brief stronger wind around the steadier wind', 'A wind that only exists above the clouds', 'The same thing as the steady wind, renamed', 'A kind of cloud that looks like a barb'],
    'A gust is a short-lived faster wind. Near the ground it arrives and goes before a small aircraft can settle.',
    M, 'Wind', pic.wind),
  row('drone.cloud-vis', 'curious', null, 'mechanism', charts,
    'Cloud is lowering over the place on the map and the view across the ground is shrinking. What are you watching?',
    ['How much sky and distance you can still see', 'A pressure setting, written as a cloud', 'A wind barb drawn to look like fog', 'The time of day, and nothing about the air'],
    'Visibility is how far you can see, and the cloud base is how much clear air is under the cloud. Both shrink the room a small aircraft has.',
    B, 'METAR guide, visibility and cloud', pic.cloud),
  row('drone.density-battery', 'curious', null, 'mechanism', physics,
    'It is hot, and a small aircraft is working hard to stay up. What is the thin air doing?',
    ['It makes the motors and wings work harder', 'It makes the flight easier because heat lifts', 'It only changes the colour of the map', 'It cools the battery so the flight lasts longer'],
    'Hot, thin air gives the wing and the propeller less to push against, so the aircraft uses more effort to do the same job.',
    M, 'Density altitude', pic.alt),
  row('drone.thunderstorm', 'curious', null, 'mechanism', physics,
    'A storm tower is on the map near your place, with rain and a sharp gust front. What travels out ahead of the rain?',
    ['A sudden wind as the storm’s cold air spreads', 'A patch of calm that is safe to linger in', 'Only thunder, with no change in the wind', 'A rise in the cloud base and better sight'],
    'The cold air from a storm spreads out at the ground as a gust front. The wind can arrive before the rain does.',
    M, 'Thunderstorms', pic.storm),
  row('drone.metar-taf', 'curious', null, 'mechanism', charts,
    'You have a short report of the weather now and a longer forecast for later. Which one tells you the air at this minute?',
    ['The short report of what is happening now', 'The forecast, because it replaces the report', 'Whichever line has the larger numbers', 'Neither, until someone redraws the map'],
    'The METAR is the observation now. The TAF is the forecast of how that weather is expected to change.',
    B, 'METAR and TAF guides', pic.map),
];

/** Small aircraft near the ground. Learning questions, never a launch clearance. */
export const droneSeeds: Seed[] = [
  row('met.pressure-systems', 'drone', null, 'mechanism', [...physics, ...ops],
    'You are learning how a small drone near the ground meets the low painted west of your place. What is that low doing to the air the drone flies in?',
    ['It is lifting the air, so cloud and gusts favour it', 'It is pressing the air down into a calm layer', 'It is a no-fly line the drone must not cross', 'It only changes the number on the altimeter'],
    'The low lifts air. A drone near the ground meets the cloud and the unsettled wind that lift brings. This is a lesson, not a decision to launch.',
    M, 'Pressure systems', pic.low),
  row('met.pressure-gradient', 'drone', null, 'mechanism', [...physics, ...ops],
    'The isobars are packed beside the beach where you fly a small drone. What does that packing mean for an aircraft near the ground?',
    ['A stronger wind, and gusts around that wind', 'A calm, because packed lines cancel the wind', 'Less lift, because lines are a temperature', 'A cloud clearance, written as a spacing'],
    'Tight isobars are a strong pressure change, so the wind near the ground is stronger. Gusts ride on top of that wind.',
    M, 'Pressure gradient', pic.tight),
  row('met.coriolis', 'drone', null, 'mechanism', physics,
    'A drone is low, where friction is large, and someone draws the wind as if the Earth were not turning. What is missing from that picture?',
    ['The turn of the Earth still bends the flow aloft', 'Friction removes pressure, so the lines vanish', 'A drone is too small for the wind to notice', 'The bend only exists on northern charts'],
    'Coriolis is weak in the story of a hover near the ground, but the wind the drone meets was bent by it on the way down.',
    M, 'Coriolis', pic.spin),
  row('met.geostrophic', 'drone', null, 'mechanism', physics,
    'You compare the wind a drone feels at head height with the wind that balances the isobars higher up. How do they differ?',
    ['The low wind is slower and crosses the lines', 'They match, because balance reaches the grass', 'The low wind is faster and follows the lines', 'The balanced wind is a temperature, not a flow'],
    'Geostrophic balance is an upper-air idea. Near the ground, friction slows the wind and turns it toward the low.',
    M, 'Geostrophic wind', pic.wind),
  row('met.gradient-wind', 'drone', null, 'mechanism', physics,
    'A small drone is flying under tightly curved isobars around a low. What does the curve add to the wind story?',
    ['The curve makes the balanced wind a little slower', 'The curve makes every surface wind a calm', 'The curve is a thunderstorm symbol', 'The curve only matters above the flight levels'],
    'Curved flow around a low is slower than the straight-line balance. The drone still feels the rough surface wind under that flow.',
    M, 'Gradient wind', pic.spin),
  row('met.surface-friction', 'drone', null, 'mechanism', [...physics, ...ops],
    'You are learning why a drone at treetop height does not feel the wind printed for a thousand feet up. What changed on the way down?',
    ['The ground slowed it and turned it toward the low', 'The ground sped it up along the isobars', 'Height never changes the wind a drone feels', 'Friction only acts on aeroplanes, not drones'],
    'Friction is strongest near the surface, which is exactly where a small drone spends its time.',
    M, 'Surface friction', pic.wind),
  row('met.buys-ballot', 'drone', 'aus', 'mechanism', physics,
    'You stand on an Australian field with the wind on your back, learning where the low sits. Where is it?',
    ['On your right, because you are south of the equator', 'On your left, as in a United States diagram', 'Straight ahead, at the end of the wind', 'Behind you, back toward the high'],
    'In Australia the low is on your right when the wind is on your back. A Part 107 diagram drawn for the United States shows the other hand.',
    M, 'Buys Ballot', pic.wind),
  row('met.temperature', 'drone', null, 'mechanism', [...physics, ...numbers],
    'A drone is climbing through the afternoon air over a hot pad. What is happening to the air it climbs through?',
    ['The air it meets is cooler the higher it goes', 'The air it meets is warmer because of the climb', 'Temperature does not change with height here', 'The heat is a battery reading, not the air'],
    'Air cools as it rises. The hot pad still means the whole column is warmer, and thinner, than a cold morning.',
    M, 'Lapse rate', pic.temp),
  row('met.moisture', 'drone', null, 'mechanism', charts,
    'The report at your flying site shows the temperature and dewpoint a degree apart. What does that gap tell a drone pilot who is still learning?',
    ['The air is nearly saturated, so cloud or fog is close', 'The air is very dry, so the gap is a good sign', 'The two numbers are wind and pressure', 'A one degree gap is a cloud clearance rule'],
    'A tiny temperature–dewpoint spread means the air is close to forming cloud. It does not, by itself, state a legal clearance.',
    B, 'METAR guide, temperature and dewpoint', pic.cloud),
  row('met.stability', 'drone', null, 'mechanism', physics,
    'You are learning how a bubble of warm air beside a hot pad behaves. What does that bubble do?',
    ['It rises while it stays warmer than its surroundings', 'It sinks because warm air wants the ground', 'It stays in one place until a front arrives', 'It only matters to airliners above the pad'],
    'An unstable bubble keeps rising. A drone near it meets the updraft and the sink beside it.',
    M, 'Stability', pic.temp),
  row('met.thunderstorm', 'drone', null, 'mechanism', [...physics, ...ops],
    'A cumulonimbus is building near the site on the map. What reaches a small aircraft near the ground before the heavy rain?',
    ['The gust front of cold air spreading out', 'A guaranteed calm under the anvil', 'Only the thunder, with the wind unchanged', 'A higher cloud base and a smoother wind'],
    'The outflow can arrive first. Learning that order is the point; it is not a clearance to fly closer and look.',
    M, 'Thunderstorms', pic.storm),
  row('met.ceiling', 'drone', null, 'mechanism', charts,
    'A report shows FEW at one height and BKN lower. Which figure is the ceiling a drone lesson should use?',
    ['The BKN base, the lowest layer covering half the sky', 'The FEW base, because it is named first', 'The average of the two heights', 'Neither, until the letters say OVC'],
    'Ceiling is the base of the lowest broken or overcast layer. FEW and SCT are not a ceiling. BoM METAR guide, cloud.',
    B, 'METAR guide, cloud', pic.cloud),
  row('met.taf-groups', 'drone', 'aus', 'mechanism', charts,
    'You are learning an Australian TAF that carries TEMPO for a gusty hour and INTER for a briefer shower. What is the difference in the spell?',
    ['TEMPO lasts longer than INTER in the same forecast', 'INTER lasts longer than TEMPO by definition', 'They are two names for one identical spell', 'Both can be skipped because a drone is small'],
    'BoM defines TEMPO as fluctuations of 30 minutes up to under 60, and INTER as under 30 minutes. The lesson is the length of the spell, not a launch call.',
    B, 'TAF guide, significant changes and variations', pic.map),
  row('met.icing', 'drone', null, 'mechanism', physics,
    'A small aircraft climbs into cloud where the air is below freezing. What can the cloud drops do to it?',
    ['Freeze onto it even though they were still liquid', 'Stay harmless because drones do not collect ice', 'Turn to snow before they can touch anything', 'Warm the airframe as they pass'],
    'Supercooled drops freeze on contact. Ice is a cloud-and-temperature problem at low level too.',
    M, 'Icing', pic.ice),
  row('met.turbulence', 'drone', null, 'mechanism', [...physics, ...ops],
    'Trees at the site are swaying in bursts while the steady wind looks moderate. What is the extra hazard in the bursts?',
    ['A gust can exceed the steady wind for a moment', 'A gust is always weaker than the steady wind', 'Bursts are a visibility code, not a wind', 'A drone averages them out and feels neither'],
    'The gust, not the steady wind, is what a light aircraft near the ground has to absorb. Read both numbers.',
    B, 'METAR guide, wind', pic.wind),
  row('met.fronts', 'drone', null, 'mechanism', physics,
    'A front is crossing the coast where you fly. What change should you expect in the wind as it passes?',
    ['A shift in direction and often a fresher gust', 'No change, because fronts are an upper-air idea', 'Only a change in the altimeter setting', 'A long calm exactly on the drawn line'],
    'A front is a change of air mass. The wind direction and the gustiness commonly shift as it passes a site.',
    M, 'Fronts', pic.rain),
  row('nav.place-time', 'drone', null, 'mechanism', charts,
    'A TAF time is in UTC and your site is on local time. What do you convert before you read the group?',
    ['The UTC window into the local clock of the site', 'Nothing, because drone reports are already local', 'The local clock into feet of cloud base', 'The date, because UTC is a wind unit'],
    'Aerodrome forecasts are in UTC. A wrong conversion puts you in the wrong hour of the forecast.',
    B, 'TAF guide, validity', pic.map),
  row('nav.great-circle', 'drone', null, 'mechanism', numbers,
    'You are learning why a long drone delivery path on a flat map looks bent on the Earth. What is the short path really?',
    ['A great circle, not the ruler line on the paper', 'The ruler line, which is always shortest', 'A line of constant latitude, by rule', 'A path that ignores the wind completely'],
    'On a sphere the short path is a great circle. For a short hop the difference is tiny; the idea still stops a flat-map mistake.',
    M, 'Great circle', pic.map),
  row('fpl.wind-component', 'drone', null, 'mechanism', [...numbers, ...ops],
    'The wind is 40 degrees off the line a drone is trying to hold. How does that wind split?',
    ['Into a component along the line and one across it', 'Into a pure headwind with nothing across', 'Into a temperature change and a cloud base', 'It does not split, because a drone has no runway'],
    'Any wind at an angle has a part along the track and a part across it. The cross part is what pushes a drone off its line.',
    M, 'Wind components', pic.wind),
  row('fpl.taf-threshold', 'drone', null, 'mechanism', charts,
    'You are learning a TAF and one group drops the visibility well below the others. What is that group for?',
    ['The spell when the view is forecast to worsen', 'A printing error you should skip', 'The present weather, replacing the METAR', 'A second site hidden in the same line'],
    'The group names a period of worse weather. You learn which period it is. You do not treat the line as a launch order.',
    B, 'TAF guide, change groups', pic.cloud),
  row('fpl.track-correction', 'drone', null, 'mechanism', [...numbers, ...ops],
    'A drone is pointed straight at a mark but the wind is from the side. What happens to its path over the ground?',
    ['It drifts downwind of the mark unless you aim upwind', 'It tracks the mark because pointing is enough', 'It climbs, because drift is a vertical error', 'The wind only matters above 400 feet'],
    'Side wind is drift. You aim into it if you want the ground track to stay on the mark. This is the geometry, not a clearance.',
    M, 'Drift', pic.drift),
  row('fpl.cruise-level', 'drone', null, 'mechanism', numbers,
    'You are learning why crewed aircraft use set heights by direction, while a drone is usually far below them. What is the drone’s separate problem?',
    ['The wind and the obstacles in the layer it actually uses', 'The same flight level table, flown at treetop height', 'A standard pressure setting of 29.92 inHg', 'No wind, because the table begins at the ground'],
    'Hemispheric cruising levels organise traffic up high. A drone’s lesson is the wind in the layer it occupies, not that table.',
    M, 'Cruising levels', pic.alt),
  row('fpl.safe-return', 'drone', null, 'mechanism', [...numbers, ...ops],
    'A battery will just get a drone home from a point on its route, and just get it onward to the pad. What is that point?',
    ['The far point where turning back still equals going on', 'The point where the battery is already empty', 'A point that only exists in a headwind of zero', 'The legal edge of the map'],
    'It is the same equality as a point of safe return: the two ways cost the same energy. Past it, home costs more than you have.',
    M, 'Point of safe return', pic.map),
  row('perf.pressure-altitude', 'drone', 'us', 'mechanism', numbers,
    'You are learning a United States altimeter setting of 29.82 inHg at a field. What is pressure altitude compared with the field elevation?',
    ['Higher, because 29.82 is below the standard 29.92', 'Lower, because a smaller number means denser air', 'Equal, because inches are only a label', 'Unrelated, because drones use hectopascals only'],
    'Standard pressure is 29.92 inHg. A lower setting means the pressure altitude is above the elevation. FAA-H-8083-28 treats the same standard air.',
    W, 'Pressure altitude', pic.alt),
  row('perf.density-altitude', 'drone', null, 'mechanism', [...physics, ...numbers],
    'You are learning a hot, high site and the battery a drone will use to hover. What does density altitude do to that hover?',
    ['It demands more power because the air is thinner', 'It saves power because heat adds lift', 'It changes the map colour and nothing else', 'It only applies to aeroplanes with wings'],
    'High density altitude thins the air. Rotors and wings both need more effort. The battery spends faster for the same hover.',
    M, 'Density altitude', pic.alt),
  row('perf.takeoff-factors', 'drone', null, 'mechanism', ops,
    'You are learning a takeoff from a short pad on a hot afternoon with a tailwind. What lengthens the distance a small aircraft needs?',
    ['The thin air and the tailwind together', 'The heat, which shortens every takeoff', 'The tailwind, which acts as extra lift', 'Neither, below a hundred feet of height'],
    'Heat raises density altitude and a tailwind steals airspeed. Both stretch the distance. The lesson is the mechanism.',
    M, 'Takeoff performance', pic.alt),
  row('perf.weight', 'drone', null, 'mechanism', numbers,
    'You clip a heavier camera to a small multirotor and leave the battery the same. What changes in the hover?',
    ['More thrust is required, so the battery spends faster', 'Nothing, because weight is only a paperwork item', 'The aircraft becomes more stable in every gust', 'The wind limit rises because mass ignores gusts'],
    'Extra mass needs extra thrust. In thin air or a gust the margin you had is smaller.',
    M, 'Weight', pic.alt),
  row('aero.lift', 'drone', null, 'mechanism', physics,
    'A gust suddenly raises the airspeed over a wing, or over a rotor disc. What happens to the lift in that instant?',
    ['Lift rises with the square of the extra speed', 'Lift falls, because a gust unloads the wing', 'Lift is unchanged until you move a control', 'Lift becomes a battery voltage'],
    'Lift grows with the square of speed. A gust is a sudden change in that speed, which is why a light aircraft kicks.',
    M, 'Lift', pic.wind),
  row('aero.induced-drag', 'drone', null, 'mechanism', physics,
    'A drone is hovering, which is the slow extreme of flight. Where is most of the power going?',
    ['Into making lift, which is expensive when you are slow', 'Into overcoming a high cruise speed', 'Into the map, as a pressure correction', 'Into nothing, because a hover is effortless'],
    'The power cost of producing lift is worst at low speed. A hover is that case.',
    M, 'Induced drag', pic.alt),
  row('aero.stall-aoa', 'drone', null, 'mechanism', physics,
    'You are learning a fixed-wing drone that pitches up in a gust until the wing’s angle is past its limit. What happens next?',
    ['The wing stalls even if the speed dial looks fine', 'The wing cannot stall below a posted speed', 'The gust adds lift and removes the stall', 'Only helicopters stall, and only in cloud'],
    'Stall is an angle, not a single speed. A gust can reach that angle.',
    M, 'Stall', pic.wind),
  row('aero.load-factor', 'drone', null, 'mechanism', physics,
    'A small aircraft banks hard while it turns near the ground. What does the turn demand of the wing or the rotors?',
    ['More lift than the weight alone, because of the bank', 'Less lift, because the turn shares the weight', 'The same lift, because a bank is only a heading', 'No extra load below four hundred feet'],
    'A level turn loads the wing above the aircraft’s weight. The steeper the bank, the more the load.',
    M, 'Load factor', pic.spin),
  row('aero.manoeuvre-speed', 'drone', null, 'mechanism', [...physics, ...ops],
    'You are learning what a sharp gust can do to a light airframe. What is the point of a manoeuvre speed?',
    ['Below it, the wing should stall before it breaks', 'Below it, the wing can take an unlimited gust', 'It is a cloud clearance, written as a speed', 'It rises when you take weight off the aircraft'],
    'Manoeuvre speed is the speed where a stall arrives before the limit load. It is lower when the aircraft is lighter, not higher.',
    M, 'Manoeuvre speed', pic.wind),
  row('sys.pitot-static', 'drone', null, 'mechanism', physics,
    'You are learning a blocked sensing tube on a small pitot. As the aircraft climbs, what does a pressure speed dial tend to do?',
    ['Read higher than the real speed during the climb', 'Fall to zero the moment the tube blocks', 'Stay correct, because drones do not use pressure', 'Show the crosswind instead of the airspeed'],
    'Trapped pitot pressure against a falling static pressure drives the dial up in the climb. The lesson is the instrument, not a repair.',
    M, 'Pitot-static', pic.alt),
  row('sys.anti-ice', 'drone', null, 'mechanism', physics,
    'Cloud and below-freezing air sit on the site forecast. What is the icing lesson for a small airframe with no protection?',
    ['Liquid drops in that cloud can freeze onto it', 'Ice requires snow already falling out of the cloud', 'A small airframe is too warm for ice to stick', 'Icing is only a problem above the flight levels'],
    'Unprotected airframes ice in supercooled cloud. Size does not grant an exemption from the physics.',
    M, 'Icing', pic.ice),
  row('sys.pressurisation', 'drone', null, 'mechanism', physics,
    'You are learning why a drone has no pressurised cabin while an airliner does. What problem is the cabin solving?',
    ['Thin air at height, which a low drone never meets', 'Icing, which a cabin melts by definition', 'Crosswind, which the cabin points into wind', 'A legal cloud clearance, measured in feet'],
    'Pressurisation keeps people in thicker air. A drone near the ground does not have that problem; the pilot on the ground still does if they were up high.',
    M, 'Pressurisation', pic.alt),
  row('hum.hypoxia', 'drone', null, 'mechanism', physics,
    'You are learning hypoxia as a pilot on the ground watching a high mountain site. Whose air is thin?',
    ['Anyone at that high site, including the person launching', 'Only people inside a pressurised cabin', 'Nobody, because oxygen stays a fifth of the air', 'Only crews above the airline transition'],
    'The oxygen fraction stays near 21 percent, but a high site has less pressure, so each breath carries less oxygen.',
    M, 'Hypoxia', pic.alt),
  row('hum.vestibular', 'drone', null, 'mechanism', physics,
    'You are learning a first-person view in cloud, where the horizon has gone and your ear says you are level. What is the reliable horizon?',
    ['The aircraft’s instruments, not the ear', 'The ear, which still feels the real horizon', 'The video noise, which points at the ground', 'The wind, which substitutes for both'],
    'Without a visual horizon the inner ear is a poor attitude instrument. The displayed horizon is the one to trust.',
    M, 'Vestibular illusions', pic.cloud),
  row('hum.fatigue-rules', 'drone', null, 'mechanism', ops,
    'You have been awake too long and you are still reading a METAR for a drone lesson. What does the fatigue change?',
    ['You are more likely to miss the gust or the cloud', 'You read the codes faster and more accurately', 'Fatigue only applies to airline duty limits', 'A tired reader treats a gust as a calm'],
    'The legal duty tables are for crewed operations. The effect that matters here is simpler: a tired reader skips the number that mattered.',
    M, 'Fatigue', pic.map),
  row('law.transition-altitude', 'drone', 'us', 'mechanism', numbers,
    'You are learning why a drone altimeter and an airliner altimeter are not doing the same job at 18,000 ft. What changes for the airliner there in the United States?',
    ['It sets 29.92 inHg and flies flight levels', 'It keeps the field setting all the way up', 'It switches to hectopascals by a drone rule', 'It stops using pressure and uses the GPS only'],
    'At and above 18,000 ft MSL the United States sets 29.92 inHg. 14 CFR 91.121. A drone near the ground is nowhere near that switch.',
    'cfr', '91.121', pic.alt),
  row('law.alternate', 'drone', null, 'mechanism', charts,
    'You are learning what an alternate means on a crewed forecast, and you fly a drone from one paddock. What is the useful idea to steal?',
    ['Know another place you can reach if this one goes poor', 'File an airline alternate for every battery', 'Ignore TEMPO groups because a drone is excluded', 'Treat the home pad as usable in any cloud'],
    'The idea is a second place you can actually get to. The airline rule that creates the legal alternate is a different card.',
    M, 'Alternates', pic.map),
  row('law.documents', 'drone', null, 'mechanism', ops,
    'You are learning which document says what a remote pilot must know, as distinct from the weather itself. What does the weather map still not do?',
    ['It does not replace the licence or the operating rules', 'It is the licence, once you can read the lines', 'It waives cloud rules when the lines are far apart', 'It sets the battery limit for the aircraft'],
    'The map is the air. The permission to fly sits in the country’s remote-pilot rules, which you learn separately.',
    M, 'Licensing', pic.map),
  row('drone.low-level-wind', 'drone', null, 'mechanism', [...ops, ...charts],
    'You are learning a METAR that reads 24015G25KT at the site. What is the 25 in that wind?',
    ['The gust, a brief wind faster than the steady 15', 'The steady wind, with 15 a visibility', 'A direction, because both numbers are degrees', 'A cloud base of 2,500 ft written without zeros'],
    'The first wind number is the steady speed and the figure after G is the gust. BoM METAR guide, wind. A small aircraft near the ground meets the gust.',
    B, 'METAR guide, wind', pic.wind),
  row('drone.cloud-vis', 'drone', 'us', 'rule', ['rules-us', 'operations'],
    'You are learning the United States cloud and visibility limits for a small unmanned aircraft in controlled airspace near the ground. What does the rule require you to keep?',
    ['Three statute miles, 500 ft under cloud and 2,000 ft horizontally', 'One mile, and you may touch the cloud base', 'The same CAVOK definition Australia prints on a TAF', 'No limit, because the aircraft is under 55 lb'],
    '14 CFR 107.51 requires 3 statute miles flight visibility and 500 ft below and 2,000 ft horizontally from cloud. This is the rule you are learning, not a clearance for a real flight.',
    'cfr', '107.51', pic.cloud),
  row('drone.cloud-vis', 'drone', 'aus', 'rule', ['rules-aus', 'operations'],
    'You are learning an Australian excluded or RePL operation near the ground, and cloud is lowering over the site. What do the standard conditions demand of the aircraft?',
    ['It stays in sight and clear of the cloud', 'It may enter the cloud if the battery allows', 'It uses the United States 500 ft rule as Australian law', 'Cloud does not matter below 400 ft at all'],
    'Part 101 MOS standard RPA operating conditions keep the aircraft in visual line of sight and clear of cloud. The lesson is that limit. It is not a decision to launch today.',
    'casa-101', 'standard RPA operating conditions', pic.cloud),
  row('drone.density-battery', 'drone', null, 'mechanism', [...numbers, ...ops],
    'You are learning a hot afternoon at an inland site and the minutes a battery used to give on a cool morning. What should you expect of those minutes?',
    ['Fewer, because thin air costs more power to hover', 'More, because heat makes the rotors efficient', 'The same, because a battery ignores the weather', 'Twice as long, because density altitude adds charge'],
    'High density altitude makes the rotors work harder, so the same hover spends the battery faster. FAA-H-8083-28, density altitude, is the same physics.',
    W, 'Density altitude', pic.alt),
  row('drone.thunderstorm', 'drone', null, 'mechanism', [...ops, ...physics],
    'You are learning a storm on the map upwind of a drone site. What is the order a new pilot should expect?',
    ['The gust front can arrive before the rain does', 'The rain always finishes before any gust', 'Thunderstorms stay on the chart and not in the wind', 'The anvil calms the air underneath it'],
    'Outflow travels along the ground ahead of the heavy rain. Learning that order is how you stay away from the storm. It is not a tactical call.',
    M, 'Thunderstorms', pic.storm),
  row('drone.metar-taf', 'drone', null, 'mechanism', charts,
    'You are learning a drone flight an hour from now. The METAR is the present wind and the TAF has a TEMPO in that hour. Which document owns the hour you care about?',
    ['The TAF’s TEMPO, with the METAR as the present picture', 'The METAR alone, because a TAF is for airlines', 'Whichever report is shorter', 'Neither, until the isobars are relabelled'],
    'The METAR is now. The TAF is the forecast, and a TEMPO in your hour is a spell of different weather inside it. BoM TAF guide, TEMPO.',
    B, 'TAF guide, TEMPO', pic.map),
];

const P = 'casa-91-mos';

/** Pilot cards. Australian rules are the ones already checked in sources.json.
 * United States cards use 14 CFR sections that are public and stable. */
export const pilotSeeds: Seed[] = [
  row('met.ceiling', 'student', 'aus', 'rule', charts,
    'You are a student pilot reading a METAR before a local flight at 03:00Z. The cloud is FEW020 BKN035. What is the ceiling?',
    ['3,500 ft, the base of the broken layer', '2,000 ft, the base of the few layer', 'There is no ceiling, because both are named', '5,500 ft, the two bases added together'],
    'A ceiling is the base of the lowest broken or overcast layer. FEW is not a ceiling. BoM METAR guide, cloud.',
    B, 'METAR guide, cloud', pic.cloud),
  row('met.taf-groups', 'student', 'aus', 'rule', charts,
    'You are a student pilot reading an Australian TAF for a lesson at 04:00Z. One group is marked TEMPO. How long is each fluctuation in that group?',
    ['From 30 minutes up to under 60 minutes', 'Under 30 minutes, the same length as INTER', 'The whole validity of the TAF', 'A full hour, and then the group expires'],
    'BoM defines TEMPO as fluctuations each lasting 30 minutes to less than 60. INTER is the shorter spell.',
    B, 'TAF guide, significant changes and variations', pic.map),
  row('law.alternate', 'student', 'aus', 'rule', ['rules-aus', 'charts'],
    'You are a student pilot planning a day VFR trip and the destination has no forecast you can use. What does the rule require?',
    ['Nominate a destination alternate', 'Depart, because a missing forecast is fine', 'Treat the METAR as if it were the TAF', 'Hold for ten minutes and then ignore it'],
    'If the required destination forecast is not available, you nominate an alternate. Part 91 MOS s 8.04.',
    P, 's 8.04 (3)', pic.cloud),
  row('fpl.wind-component', 'student', 'aus', 'rule', charts,
    'You are a student pilot turning a METAR wind onto a runway. The report says 24015KT. What direction is 240?',
    ['Degrees true, not the runway’s magnetic number', 'Degrees magnetic, already aligned with the runway', 'A visibility of 240 metres in the rain', 'A cloud base of 2,400 ft written short'],
    'METAR and TAF wind directions are degrees true. The runway number is magnetic. BoM METAR guide, wind.',
    B, 'METAR guide, wind', pic.wind),
  row('met.ceiling', 'student', 'aus', 'rule', charts,
    'You are a student pilot and the METAR says CAVOK. What are you entitled to read from that one word?',
    ['Visibility at least 10 km and no low cloud or CB', 'A ceiling of 2,000 ft and rain nearby', 'That the wind is calm and the QNH is 1013', 'That an alternate is required on arrival'],
    'CAVOK means visibility 10 km or more, no cloud below 5,000 ft or the highest MSA, no CB or TCU, and no significant weather. BoM METAR guide, CAVOK.',
    B, 'METAR guide, CAVOK', pic.cloud),
  row('fpl.taf-threshold', 'student', 'aus', 'rule', ['rules-aus', 'charts'],
    'You are a student pilot and your ETA is 04:00Z. From when until when must the destination forecast be valid?',
    ['From 30 minutes before the ETA to 60 after', 'Only at the exact minute of the ETA', 'From an hour before until an hour after', 'For the whole civil day of the flight'],
    'The forecast has to cover from at least 30 minutes before the ETA to 60 minutes after it. Part 91 MOS s 7.02.',
    P, 's 7.02 (6)', pic.map),
  row('law.transition-altitude', 'student', 'us', 'rule', ['rules-us', 'numbers'],
    'You are a student pilot in the United States climbing through 18,000 ft MSL at 16:00Z. The field altimeter was 30.05 inHg. What do you set?',
    ['29.92 inHg as you enter the flight levels', '30.05 inHg for the rest of the climb', '1013 hPa, because flight levels are metric', 'The field elevation, in inches of mercury'],
    'At and above 18,000 ft MSL you set 29.92 inHg. 14 CFR 91.121. FAA-S-ACS-6 expects that switch.',
    'cfr', '91.121', pic.alt),
  row('perf.pressure-altitude', 'student', 'us', 'rule', ['rules-us', 'numbers'],
    'You are a student pilot on the ramp in Colorado and the altimeter setting is 30.12 inHg. Which subscale are you holding?',
    ['Inches of mercury, not hectopascals', 'Hectopascals, the same figure as a QNH', 'Millibars above 18,000 ft only', 'A density altitude, already corrected'],
    'United States altimeter settings are in inches of mercury. 14 CFR 91.121 states the setting you use. 30.12 inHg is that setting, not a hectopascal QNH.',
    'cfr', '91.121', pic.alt),
  row('met.buys-ballot', 'student', 'us', 'mechanism', physics,
    'You are a student pilot in the contiguous United States with the wind at your back. Where is the low?',
    ['On your left, the northern-hemisphere side', 'On your right, as it would be in Australia', 'Straight ahead, at the end of the wind', 'Behind you, under the high'],
    'North of the equator the low is on your left when the wind is on your back. FAA-H-8083-28, wind. An Australian diagram is the other hand.',
    W, 'Wind', pic.wind),
  row('law.alternate', 'student', 'us', 'rule', ['rules-us', 'charts'],
    'You are a student pilot filing IFR to a destination with an approach, ETA 18:00Z. From 17:00Z to 19:00Z the ceiling is forecast 1,500 ft and the visibility 2 miles. Is an alternate required?',
    ['Yes, the 1-2-3 ceiling and visibility are not met', 'No, because an approach is published there', 'No, because 1,500 ft is above the minimum', 'Yes, but only when the wind is over 20 kt'],
    '14 CFR 91.169 needs no alternate only when, from an hour before to an hour after, the ceiling is at least 2,000 ft and the visibility at least 3 statute miles. This forecast is under both.',
    'cfr', '91.169', pic.cloud),

  row('met.ceiling', 'commercial', 'aus', 'rule', charts,
    'You are a commercial pilot planning a charter into a coastal aerodrome at 06:00Z. The TAF shows SCT012 BKN025. For a ceiling, which layer counts?',
    ['BKN025, because broken cloud is a ceiling', 'SCT012, because it is the lower layer', 'Both layers, added into one ceiling', 'Neither, unless the TAF also says CAVOK'],
    'Ceiling is the lowest BKN or OVC. SCT is not a ceiling. BoM TAF guide, cloud, and the same definition the METAR uses.',
    B, 'TAF guide, cloud', pic.cloud),
  row('met.taf-groups', 'commercial', 'aus', 'rule', charts,
    'You are a commercial pilot and the destination TAF carries INTER for a shower around your ETA of 05:00Z. How long is each INTER fluctuation?',
    ['Less than 30 minutes at a time', 'From 30 minutes up to under 60', 'The entire INTER period without a break', 'One minute, because INTER means instant'],
    'BoM defines INTER as fluctuations each lasting less than 30 minutes. TEMPO is the longer of the two spells.',
    B, 'TAF guide, significant changes and variations', pic.rain),
  row('law.alternate', 'commercial', 'aus', 'rule', ['rules-aus', 'charts'],
    'You are a commercial pilot and the destination TAF shows relevant weather as INTER through your ETA. How much holding fuel stands in for an alternate?',
    ['30 minutes, the INTER holding figure', '60 minutes, because every group is TEMPO', 'None, because INTER can be ignored', '15 minutes, the final reserve alone'],
    'For relevant weather forecast as INTER, 30 minutes of holding fuel. TEMPO is 60. Part 91 MOS s 8.04.',
    P, 's 8.04 (6)', pic.cloud),
  row('met.taf-groups', 'commercial', 'aus', 'rule', charts,
    'You are a commercial pilot looking at a TEMPO group that covers your ETA. How much holding fuel does that TEMPO represent under Part 91?',
    ['60 minutes of holding, in place of an alternate', '30 minutes, the same figure as an INTER', 'No holding, because TEMPO is below 50 percent', 'The final reserve, and nothing more'],
    'A TEMPO of relevant weather is planned with 60 minutes of holding fuel. Part 91 MOS s 8.04. BoM still defines the spell as 30 minutes to under 60.',
    P, 's 8.04 (6)', pic.map),
  row('met.turbulence', 'commercial', 'aus', 'rule', charts,
    'You are a commercial pilot and a SIGMET for severe turbulence has just been issued. What is the longest it can stay valid?',
    ['Four hours, unless it is cancelled sooner', 'Six hours, the figure used for every SIGMET', 'Thirty minutes, the same length as INTER', 'Until the next TAF, with no limit of its own'],
    'A SIGMET is valid for no more than 4 hours. Volcanic ash and tropical cyclone SIGMETs may last 6. BoM SIGMET guide, validity.',
    B, 'SIGMET guide, validity and cancellation', pic.wind),
  row('fpl.taf-threshold', 'commercial', 'aus', 'rule', ['rules-aus'],
    'You are a commercial pilot and your ETA falls 20 minutes before a TEMPO of relevant weather begins. Does the alternate window catch you?',
    ['Yes, the window starts 30 minutes before the weather', 'No, because you arrive before the TEMPO starts', 'No, unless the TEMPO is also an INTER', 'Yes, but only for a flight that is IFR'],
    'The alternate window runs from 30 minutes before the forecast start of the relevant weather. Part 91 MOS s 8.04.',
    P, 's 8.04 (1)', pic.map),
  row('law.transition-altitude', 'commercial', 'us', 'rule', ['rules-us', 'numbers'],
    'You are a commercial pilot departing Denver at 15:00Z, passing 18,000 ft with 30.18 on the subscale. What do you set for the flight levels?',
    ['29.92 inHg from 18,000 ft upward', '30.18 inHg until you reach the first level', '1013 hPa, converted and set as inches', 'The elevation of Denver, in inches'],
    '14 CFR 91.121 requires 29.92 inHg at and above 18,000 ft MSL. The field setting stops at the transition.',
    'cfr', '91.121', pic.alt),
  row('met.pressure-systems', 'commercial', 'us', 'rule', ['rules-us', 'charts'],
    'You are a commercial pilot in the United States reading a METAR altimeter group of A3012. What number is that?',
    ['30.12 inHg, the altimeter setting', '3012 hPa, a sea-level pressure', '30.12 degrees, a wind direction', '3,012 ft, a cloud base'],
    'The United States METAR altimeter group is inches of mercury. 14 CFR 91.121 is the setting rule. A3012 means 30.12 inHg, not a hectopascal QNH.',
    'cfr', '91.121', pic.alt),
  row('met.geostrophic', 'commercial', 'us', 'mechanism', physics,
    'You are a commercial pilot looking at a United States schematic of geostrophic wind. Which side of the wind is the high?',
    ['The high is on the right of the wind', 'The high is on the left, as in Australia', 'The high is ahead, where the wind points', 'The diagram has no high, only a low'],
    'In the northern hemisphere the high sits on the right of the geostrophic wind. FAA-H-8083-28, wind. The Australian picture puts the high on the left.',
    W, 'Wind', pic.spin),
  row('law.alternate', 'commercial', 'us', 'rule', ['rules-us', 'charts'],
    'You are a commercial pilot under Part 91, ETA 20:00Z, and from 19:00Z to 21:00Z the forecast is ceiling 3,000 ft and visibility 5 miles. Do you need an alternate?',
    ['No, the hour each side meets 2,000 ft and 3 miles', 'Yes, because every IFR flight needs one', 'Yes, because 5 miles is under the rule', 'No, because Part 91 has no alternate rule'],
    '14 CFR 91.169 allows you to skip the alternate when the forecast from one hour before to one hour after shows at least 2,000 ft and 3 statute miles. This one does.',
    'cfr', '91.169', pic.cloud),

  row('met.ceiling', 'airline', 'aus', 'rule', charts,
    'You are planning an airline arrival at Sydney at 18:00Z, which is 05:00 Sydney time during Eastern Daylight. The TAF shows FEW010 SCT020 BKN040. What ceiling do you brief?',
    ['4,000 ft, the broken layer and not the few', '1,000 ft, the first cloud that is named', '2,000 ft, because scattered is enough', 'No ceiling, because the TAF is not a METAR'],
    'Ceiling is the lowest BKN or OVC. FEW and SCT do not make one. BoM TAF guide, cloud.',
    B, 'TAF guide, cloud', pic.cloud),
  row('met.taf-groups', 'airline', 'aus', 'rule', charts,
    'You are planning Perth to Sydney, arriving 15:00Z, which is 02:00 Sydney time. The TAF includes TEMPO 1414/1418 BKN010. How do you treat the length of each TEMPO spell?',
    ['Each spell is 30 minutes up to under an hour', 'Each spell is under 30 minutes, like INTER', 'The TEMPO is continuous from 14:00Z to 18:00Z', 'The TEMPO is a printing note you can drop'],
    'BoM defines each TEMPO fluctuation as 30 minutes to less than 60, inside the stated period. The period itself is not one unbroken spell.',
    B, 'TAF guide, significant changes and variations', pic.cloud),
  row('law.alternate', 'airline', 'aus', 'rule', ['rules-aus', 'charts'],
    'You are planning an Australian airline sector and the destination forecast shows relevant weather as TEMPO at your ETA of 12:00Z. How much holding fuel replaces the alternate?',
    ['60 minutes, the TEMPO figure in Part 91', '30 minutes, because TEMPO is the short group', 'None, because airline flights ignore TEMPO', '45 minutes, the piston final reserve'],
    'TEMPO relevant weather is planned with 60 minutes of holding fuel in lieu of an alternate. Part 91 MOS s 8.04.',
    P, 's 8.04 (6) and (7)', pic.map),
  row('law.alternate', 'airline', 'aus', 'rule', ['rules-aus'],
    'You are dispatching an Australian flight and the destination has no forecast for the ETA at 09:00Z. What must the plan include?',
    ['A destination alternate, because the forecast is missing', 'No alternate, if the METAR is currently good', 'A note that the crew will decide on arrival', 'Holding fuel of ten minutes and nothing else'],
    'No required destination forecast means a destination alternate. Part 91 MOS s 8.04.',
    P, 's 8.04 (3)', pic.map),
  row('met.turbulence', 'airline', 'aus', 'rule', charts,
    'You are an airline crew and a SIGMET for severe icing is issued at 02:00Z. What is the latest it can remain in force without a renewal?',
    ['06:00Z, four hours after it was issued', '08:00Z, the six hour volcanic-ash figure', '02:30Z, because every SIGMET is half an hour', 'The end of the TAF, whatever hour that is'],
    'Severe icing SIGMETs are valid for no more than 4 hours. BoM SIGMET guide, validity. Ash and cyclone SIGMETs are the ones that may reach 6.',
    B, 'SIGMET guide, validity and cancellation', pic.ice),
  row('fpl.wind-component', 'airline', 'aus', 'rule', ['charts', 'numbers'],
    'You are an airline crew briefing a crosswind at Perth. The METAR wind is 27020KT and the runway is 21. What must you not do to the 270 before you resolve it?',
    ['Treat 270 as magnetic and skip the variation', 'Remember that 270 is degrees true', 'Resolve it into a headwind and a crosswind', 'Compare it with the aircraft limit'],
    'The 270 is degrees true. The runway is magnetic. BoM METAR guide, wind. Variation is applied when you need a magnetic heading, and it is not invented.',
    B, 'METAR guide, wind', pic.wind),
  row('law.transition-altitude', 'airline', 'us', 'rule', ['rules-us', 'numbers'],
    'You are the pilot of a transport aeroplane leaving a coastal airport at 18:00Z, which is mid-afternoon locally, climbing through 18,000 ft MSL. The field setting is 29.82 inHg. What do you set as you enter the flight levels?',
    ['29.92 inHg, the standard setting above the transition', '29.82 inHg, the field setting, for the cruise', '1013 hPa on a subscale marked in inches', 'The airport elevation, expressed in inches'],
    'At and above 18,000 ft MSL the altimeter is set to 29.92 inHg. 14 CFR 91.121. FAA-S-ACS-11, regulations, expects that call.',
    'cfr', '91.121', pic.alt),
  row('law.alternate', 'airline', 'us', 'rule', ['rules-us', 'charts'],
    'You are dispatching a Part 91 ferry of a transport aeroplane, ETA 21:00Z. From 20:00Z to 22:00Z the forecast ceiling is 1,800 ft and the visibility is 4 miles. What does 91.169 require?',
    ['An alternate, because the ceiling is under 2,000 ft', 'No alternate, because visibility is over 3 miles', 'An alternate only if the flight is Part 121', 'No alternate, because a transport aircraft is exempt'],
    '14 CFR 91.169 requires both the ceiling and the visibility test: at least 2,000 ft and 3 statute miles from an hour before to an hour after. The ceiling fails, so you plan an alternate. FAA-S-ACS-11.',
    'cfr', '91.169', pic.cloud),
  row('met.buys-ballot', 'airline', 'us', 'mechanism', physics,
    'You are an ATP applicant looking at a northern-hemisphere analysis with the wind drawn along the isobars. Which side of that wind is the low?',
    ['The low is on the left of the wind', 'The low is on the right, the Australian rule', 'The low is upwind, behind the flow', 'The low is wherever the tightest line sits'],
    'In the northern hemisphere the low is on the left when you look downwind. FAA-H-8083-28, wind. Australia puts the low on the right. The diagrams are not translations.',
    W, 'Wind', pic.spin),
  row('perf.density-altitude', 'airline', 'us', 'mechanism', [...numbers, ...physics],
    'You are an ATP applicant given a hot high airport in the United States, elevation 5,000 ft, temperature well above ISA, altimeter 29.80 inHg. What happens to the takeoff distance?',
    ['It increases, because the air is thinner than ISA', 'It decreases, because heat shortens the roll', 'It is unchanged, because elevation is already known', 'It depends only on the runway number'],
    'Hot, high and a low altimeter setting all raise density altitude, and the takeoff distance grows. FAA-H-8083-28 and the PHAK, density altitude. The inputs are United States units. The physics is the same everywhere.',
    W, 'Density altitude', pic.alt),
];

/** Weather effects for a new recruit. Picture first. No targeting and no tactics. */
export const defenceSeeds: Seed[] = [
  row('def.illumination', 'defence', null, 'rule', ops,
    'The map is over your place at dusk and the moon is a thin crescent low in the east. What does that moon give you tonight?',
    ['A little light, late, and a dark first half', 'A full moon from the moment the sun sets', 'No light at all, because a crescent is dark', 'Daylight, because the moon replaces the sun'],
    'A thin moon late in the night leaves the early night dark. JP 3-59, light and illumination data.',
    'jp-3-59', 'light and illumination', pic.moon),
  row('def.illumination', 'defence', null, 'rule', ops,
    'You are learning sunrise at the place on the map. The sun is still below the horizon and the sky is already pale. What is that pale period?',
    ['Twilight, light before the sun itself is up', 'Noon, because pale means the sun is high', 'A moonrise, whatever the clock says', 'A cloud deck, with no change in the light'],
    'Twilight is usable light while the sun is still below the horizon. JP 3-59, astronomical and light data.',
    'jp-3-59', 'astronomical data', pic.moon),
  row('def.trafficability', 'defence', null, 'rule', [...ops, ...physics],
    'A rain band has just crossed the ground on your map. What happens to wheeled movement on that soil?',
    ['The ground softens and wheels sink more', 'The ground hardens as soon as it is wet', 'Rain changes the wind and not the soil', 'Only a sealed road notices the rain'],
    'Rain reduces soil strength, so wheels and tracks sink. ATP 2-01.3, weather effects on trafficability.',
    'atp-2-01-3', 'weather effects on trafficability', pic.soil),
  row('def.trafficability', 'defence', null, 'rule', ops,
    'The rain band on the map ended this morning and the ground is still soft at noon. What are you waiting for?',
    ['Time for the soil to drain and firm up', 'The next rain, which hardens wet ground', 'A change in the isobars, which dries soil', 'Moonrise, which sets the soil strength'],
    'Soil stays soft after the rain has passed, until it drains. ATP 2-01.3, trafficability.',
    'atp-2-01-3', 'trafficability', pic.soil),
  row('def.sea-state', 'defence', null, 'rule', [...ops, ...physics],
    'The isobars are packed over the coastal water on your map. What happens to a small boat there?',
    ['The sea builds as the wind stays on the water', 'The sea goes flat because tight lines are calm', 'Only the tide changes, and the wind does not', 'The boat rises because pressure lifts the hull'],
    'A tight gradient is a strong wind, and wind over water builds sea state. JP 3-59, oceanographic effects.',
    'jp-3-59', 'oceanographic effects', pic.sea),
  row('def.sea-state', 'defence', null, 'rule', ops,
    'You are learning a small craft crossing a current that runs against the wind. What does that opposition do to the waves?',
    ['It makes the waves steeper and shorter', 'It flattens the sea whatever the wind is', 'It only changes the compass, not the waves', 'It stops the current until the wind drops'],
    'Wind against a current stacks short steep waves. JP 3-59, sea state and currents.',
    'jp-3-59', 'sea state and currents', pic.sea),
  row('def.winds-aloft', 'defence', null, 'rule', [...ops, ...physics],
    'A parachute leaves the aircraft on a line and the wind aloft is across that line. What happens on the way down?',
    ['The parachute drifts off the line, downwind', 'The parachute follows the line the air ignores', 'The drift is only a problem near the ground', 'A crosswind brings the parachute back upwind'],
    'Winds aloft carry a parachute, or a drone, off the line you wanted. JP 3-59, winds and airborne operations.',
    'jp-3-59', 'winds aloft', pic.drift),
  row('def.ceiling-vis', 'defence', null, 'rule', [...ops, ...charts],
    'Cloud bases are lowering and the view along the ground is shrinking on the map. What do aircraft need before they can use a field?',
    ['Enough ceiling and enough sight to the field', 'Only a favourable wind, whatever the cloud', 'A full moon, which replaces the ceiling', 'Tight isobars, which clear the cloud'],
    'Air operations need ceiling and visibility together. JP 3-59, ceiling and visibility effects.',
    'jp-3-59', 'ceiling and visibility', pic.cloud),
  row('def.thermal-crossover', 'defence', null, 'rule', [...ops, ...physics],
    'After sunset the ground and the objects on it cool at different rates. What happens to a heat picture of the scene?',
    ['The contrast fades as their temperatures cross', 'The contrast grows all night without a pause', 'Heat pictures ignore temperature and show colour', 'Crossover is a wind shift, not a temperature'],
    'When object and background temperatures meet, a thermal picture loses contrast. ATP 2-01.3, thermal crossover. This is the effect, not a way to hide.',
    'atp-2-01-3', 'thermal crossover', pic.thermal),
  row('def.downwind-hazard', 'defence', null, 'rule', [...ops, ...physics],
    'Smoke is leaving a fire on your map and the wind is from the west. Where does the hazard travel?',
    ['Downwind, to the east of the fire', 'Upwind, back toward the west', 'Straight up, with no horizontal travel', 'Toward the nearest low, whatever the wind'],
    'The hazard area of smoke or a similar plume lies downwind. JP 3-59, downwind hazard areas. The lesson is where the plume goes, not how to use it.',
    'jp-3-59', 'downwind hazard areas', pic.hazard),
];

