// Generated by tools/clouds/pack-painted.mjs from the approved phase-1 WebPs.
export const SPRITE_RECTS = {
  "cumulus": [
    2,
    2,
    650,
    304
  ],
  "cumulonimbus": [
    2,
    310,
    734,
    438
  ],
  "cirrus": [
    2,
    752,
    688,
    311
  ],
  "stratus": [
    2,
    1067,
    768,
    68
  ],
  "nimbostratus": [
    2,
    1139,
    768,
    148
  ]
} as const;
