#import "aircraft.h"

NSArray<NSDictionary *> *AircraftRecognitionCards(void) {
    static NSArray *cards; static dispatch_once_t once;
    dispatch_once(&once, ^{ cards=@[
        @{ @"name": @"plane",
           @"title": @"Light piston",
           @"nickname": @"Sunday flyer",
           @"recognition": @"Single prop, high wing, short nose.",
           @"history": @"The flying-club regular: lessons, circuits and little adventures.",
           @"source": @"https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/phak",
           @"height": @914.4 },
        @{ @"name": @"glider",
           @"title": @"Sailplane",
           @"nickname": @"Thermal hunter",
           @"recognition": @"Long slim wings, no prop, sleek fuselage.",
           @"history": @"Soaring on lift without an engine.",
           @"source": @"https://www.faa.gov/regulations_policies/handbooks_manuals/aviation/glider_handbook/gfh_chapter_9.pdf",
           @"height": @2438.4 },
        @{ @"name": @"pc9",
           @"title": @"Pilatus PC-9",
           @"nickname": @"Roulette veteran",
           @"recognition": @"Tandem bubble canopy, single turboprop, low wing.",
           @"history": @"Trained RAAF pilots; flew with the Roulettes from 1989 to 2019.",
           @"source": @"https://www.airforce.gov.au/community/event-participation/air-force-roulettes",
           @"height": @5486.4 },
        @{ @"name": @"kingair",
           @"title": @"King Air B200",
           @"nickname": @"Working royalty",
           @"recognition": @"T tail and oval passenger windows.",
           @"history": @"Twin turboprop for regional and utility work.",
           @"source": @"https://beechcraft.txtav.com/KINGAIR",
           @"height": @7315.2 },
        @{ @"name": @"jumbo",
           @"title": @"Boeing 747",
           @"nickname": @"Queen of the skies",
           @"recognition": @"Forward upper deck hump, four under-wing jets.",
           @"history": @"First flew 1969; long-haul widebody icon.",
           @"source": @"https://www.boeing.com/commercial/747-8",
           @"height": @10668 },
        @{ @"name": @"u2",
           @"title": @"U-2",
           @"nickname": @"Dragon lady",
           @"recognition": @"Very long straight wings; one slender jet fuselage.",
           @"history": @"First flew 1955; high-altitude reconnaissance.",
           @"source": @"https://www.lockheedmartin.com/en-us/news/features/history/u2.html",
           @"height": @16764 },
        @{ @"name": @"sr71",
           @"title": @"SR-71 Blackbird",
           @"nickname": @"Fast company",
           @"recognition": @"Sharp chines, twin engine nacelles on delta wing.",
           @"history": @"First flew 1964; Mach 3 strategic reconnaissance.",
           @"source": @"https://www.lockheedmartin.com/en-us/news/features/history/blackbird.html",
           @"height": @19812 },
    ]; });
    return cards;
}
