/** Generates the Isobar B727 handbook tables into `data/*.json` from `model.ts`.
 *
 *   cd training && node --experimental-strip-types src/b727/generate.ts
 *
 * Every table is laid out the way an airline abbreviated handbook lays it out:
 * weights in 2,000 kg columns, levels as FL, ISA deviation in the steps the
 * CASA information book expects candidates to round to (3 °C for cruise fuel
 * flow, 5 °C for climb and holding). Units: kg, FL, kt, nm, min, kg/h, m.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import * as m from './model.ts';

export const WEIGHTS = range(50000, 86000, 2000);
export const CRUISE_LEVELS = range(150, 390, 10);
export const CLIMB_LEVELS = range(150, 390, 10);
export const CLIMB_WEIGHTS = range(56000, 86000, 2000);
export const CLIMB_ISA = [-10, -5, 0, 5, 10, 15, 20];
export const CAPABILITY_ISA = [-10, -5, 0, 5, 10, 15, 20];
export const DESCENT_LEVELS = [...range(150, 390, 10).reverse(), 100];
export const DESCENT_WEIGHTS = [50000, 60000, 70000];
export const HOLDING_LEVELS = [15, 50, 100, 150, 200, 250, 300, 350];
export const ONE_INOP_LEVELS = [100, 140, 180, 200, 220, 240, 260];
export const ONE_INOP_HOLDING_LEVELS = [15, 50, 100, 150, 200];
export const DRIFTDOWN_FROM = [310, 330, 350];
export const DP_LEVELS = [100, 140];
export const LOW_LEVELS = [100, 150, 200, 250];
export const INTEGRATED_LEVELS = [290, 310, 330, 350, 370];
export const INTEGRATED_WEIGHTS = range(50000, 86000, 1000);
export const TAKEOFF_PA = [0, 1000, 2000, 3000, 4000, 6000, 8000];
export const TAKEOFF_OAT = [0, 10, 20, 30, 40, 50];
export const TAKEOFF_LENGTHS = range(1500, 4500, 250);
export const LANDING_PA = [0, 2000, 4000, 6000, 8000];
export const LANDING_LENGTHS = range(1200, 3400, 100);
export const LANDING_OAT = [0, 10, 20, 30, 40, 50];
export const FUEL_INDEX_STEPS = range(0, 32000, 1000);

export function range(from: number, to: number, step: number): number[] {
  const out: number[] = [];
  for (let x = from; x <= to + 1e-9; x += step) out.push(Math.round(x * 1000) / 1000);
  return out;
}

const r0 = (x: number) => Math.round(x);
const r1 = (x: number) => Math.round(x * 10) / 10;
const r3 = (x: number) => Math.round(x * 1000) / 1000;
const down100 = (x: number) => Math.floor(x / 100) * 100;
const r10 = (x: number) => Math.round(x / 10) * 10;

const HEADER = {
  title: 'Isobar B727 Handbook data',
  aircraft: m.AIRCRAFT.type,
  engines: m.AIRCRAFT.engines,
  notice: 'Isobar model for training, not for operational use. Generated by training/src/b727/generate.ts.',
};

export function limitations() {
  const vSpeeds = WEIGHTS.map((w) => ({
    kg: w,
    takeoff: Object.fromEntries(m.TAKEOFF_FLAPS.map((f) => [f, m.takeoffSpeeds(w, f)])),
    vref: Object.fromEntries(m.LANDING_FLAPS.map((f) => [f, r0(m.vrefKias(w, f))])),
    stallClean: r0(m.stallKias(w, 0)),
  }));
  return {
    ...HEADER,
    weights: m.AIRCRAFT.weights,
    fuel: m.AIRCRAFT.fuel,
    wing: m.AIRCRAFT.wing,
    limits: m.AIRCRAFT.limits,
    climbSchedule: m.CLIMB_SCHEDULE,
    descentSchedule: m.DESCENT_SCHEDULE,
    vSpeeds,
    ruleOfThumb: {
      cruiseKgPerGroundNm: 10,
      cruiseKgPerMin: 80,
      climbExtraKg: 1600,
      note: 'Trip fuel ≈ 10 kg/gnm + 1,600 kg; cruise burn ≈ 80 kg/min. A cross-check, never the plan.',
    },
  };
}

export function fuelPolicy() {
  return {
    ...HEADER,
    title: 'Isobar company fuel policy (Part 121 style)',
    taxiKg: 200,
    apuKgPerHour: m.APU_KG_PER_HOUR,
    approachAndLandingKg: 350,
    components: [
      { id: 'taxi', name: 'Taxi fuel', rule: '200 kg from engine start to brake release. Isobar company policy.', basis: 'company' },
      { id: 'trip', name: 'Trip fuel', rule: 'Climb from brake release (Table 2.1), cruise (Section 3), descent to 1,500 ft overhead destination (Table 4.1) and the approach and landing allowance of 350 kg.', basis: 'company' },
      { id: 'contingency', name: 'Contingency fuel (variable reserve)', rule: '5% of trip fuel, but not less than 5 minutes holding at 1,500 ft above the destination at the planned landing weight (Table 4.2).', basis: 'Part 121 MOS 2020 s 7.03 (2)' },
      { id: 'alternate', name: 'Destination alternate fuel', rule: 'Missed approach, climb (Table 2.1 from the climb-out allowance), cruise, descent to 1,500 ft and the 350 kg approach allowance at the alternate. Without an alternate: 15 minutes holding at 1,500 ft above the destination.', basis: 'Part 121 MOS 2020 s 7.02 (1) and (3)' },
      { id: 'final', name: 'Final reserve', rule: '30 minutes holding at 1,500 ft above the aerodrome at the planned landing weight (Table 4.2, ISA). For before-flight planning a fixed 1,600 kg may be used.', basis: 'Part 121 MOS 2020 s 1.04, final reserve fuel' },
      { id: 'holding', name: 'Weather holding', rule: 'INTER: 30 minutes; TEMPO: 60 minutes; both at 1,500 ft holding at the planned landing weight. Isobar company policy mirroring the Australian holding requirement for forecast deteriorations.', basis: 'company' },
      { id: 'additional', name: 'Additional fuel', rule: 'Where an engine failure or depressurisation at the most critical point would require it: proceed to an alternate, hold 15 minutes at 1,500 ft, approach and land. Covered by the ETP/1-INOP and ETP/DP checks in Section 5.', basis: 'Part 121 MOS 2020 s 1.04, additional fuel' },
      { id: 'discretionary', name: 'Discretionary fuel', rule: 'At the pilot in command’s discretion.', basis: 'Part 121 MOS 2020 s 7.05 (1)' },
    ],
    aerodromeStatus: {
      suitable: 'Forecast within landing minima and no holding required for the period of possible use.',
      acceptable: 'Forecast requires INTER or TEMPO holding but the aerodrome remains usable with that holding carried; good enough for a depressurised or 1-INOP diversion.',
    },
    citations: {
      'Part 121 MOS 2020': 'https://www.legislation.gov.au/F2020L01561/latest/text',
    },
  };
}

export function climbTables() {
  const table = CLIMB_ISA.map((isa) =>
    CLIMB_LEVELS.map((fl) =>
      CLIMB_WEIGHTS.map((w) => {
        const leg = m.climb(w, fl, isa);
        return leg ? { t: r0(leg.timeMin), f: r10(leg.fuelKg), d: r0(leg.distNm) } : null;
      }),
    ),
  );
  return {
    ...HEADER,
    title: 'Table 2.1 Climb from brake release: time (min), fuel (kg), distance (nam)',
    schedule: m.CLIMB_SCHEDULE,
    takeoffAllowance: m.TAKEOFF_ALLOWANCE,
    isaDev: CLIMB_ISA,
    fl: CLIMB_LEVELS,
    brakeReleaseKg: CLIMB_WEIGHTS,
    /** table[isaIndex][flIndex][weightIndex] */
    table,
    notes: [
      'Enter with brake-release weight and the ISA deviation at 2/3 of the climb, to the nearest 5 °C.',
      'A blank means the aeroplane cannot hold 300 ft/min to that level at that weight.',
      'Time and distance are used as printed; interpolated fractions are kept. Fuel is rounded to the nearest kg when interpolated.',
      'Climb TAS = distance (nam) ÷ time (min) × 60.',
    ],
  };
}

export function altitudeCapability() {
  const m080 = CAPABILITY_ISA.map((isa) => CRUISE_LEVELS.map((fl) => {
    const w = m.thrustLimitedWeightKg(0.8, m.air(fl * 100, isa));
    return w === null ? null : down100(Math.min(w, 120000));
  }));
  const lrc = CAPABILITY_ISA.map((isa) => CRUISE_LEVELS.map((fl) => {
    const a = m.air(fl * 100, isa);
    let lo = 40000, hi = 120000;
    const ok = (w: number) => {
      const pt = m.longRangeCruise(w, a);
      return m.residualClimbFpm(w, pt.mach, a, 3 * m.maxCruiseThrustN(a)) >= 300 && pt.cl <= m.PARAMETERS.AERO.buffetCl;
    };
    if (!ok(lo)) return null;
    for (let i = 0; i < 30; i++) {
      const mid = 0.5 * (lo + hi);
      if (ok(mid)) lo = mid; else hi = mid;
    }
    return down100(lo);
  }));
  const optimum = WEIGHTS.map((w) => {
    let best = 0, bestFl = 0;
    for (const fl of CRUISE_LEVELS) {
      const a = m.air(fl * 100);
      const pt = m.longRangeCruise(w, a);
      if (pt.cl > m.PARAMETERS.AERO.buffetCl) continue;
      if (m.residualClimbFpm(w, pt.mach, a, 3 * m.maxCruiseThrustN(a)) < 300) continue;
      if (pt.narPerKg > best) { best = pt.narPerKg; bestFl = fl; }
    }
    return bestFl;
  });
  return {
    ...HEADER,
    title: 'Table 2.5 Altitude capability: thrust-limited gross weight (kg) with 300 ft/min in hand at max cruise thrust, and optimum level',
    isaDev: CAPABILITY_ISA,
    fl: CRUISE_LEVELS,
    /** m080[isaIndex][flIndex] = max GW kg at M 0.80 */
    m080,
    lrc,
    optimum: { weightKg: WEIGHTS, fl: optimum },
    notes: [
      'Enter with gross weight at the start of the cruise sector and ISA deviation at the level closest to the cruise level, to the nearest 5 °C.',
      'Highest appropriate level: the highest IFR level whose thrust-limited weight is not below the start-of-cruise weight.',
      'Optimum level: the level of best specific range at LRC, within the thrust and 1.3 g buffet limits, at the estimated mid-zone weight.',
    ],
  };
}

function cruiseGrid(levels: number[], weights: number[], speed: (w: number, a: m.Air) => m.CruisePoint | null) {
  const ff: (number | null)[][] = [];
  const tas: (number | null)[][] = [];
  const mach: (number | null)[][] = [];
  for (const fl of levels) {
    const a = m.air(fl * 100);
    const rowF: (number | null)[] = [], rowT: (number | null)[] = [], rowM: (number | null)[] = [];
    for (const w of weights) {
      const pt = speed(w, a);
      const feasible = pt && pt.kias <= m.AIRCRAFT.limits.vmoKias && m.residualClimbFpm(w, pt.mach, a, 3 * m.maxCruiseThrustN(a)) >= 0 && pt.cl <= m.PARAMETERS.AERO.buffetCl + 0.05;
      rowF.push(feasible ? r0(pt.fuelFlowKgPerHour) : null);
      rowT.push(feasible ? r0(pt.tasKt) : null);
      rowM.push(feasible ? r3(pt.mach) : null);
    }
    ff.push(rowF); tas.push(rowT); mach.push(rowM);
  }
  return { ff, tas, mach };
}

export function cruiseTables() {
  const m080 = cruiseGrid(CRUISE_LEVELS, WEIGHTS, (w, a) => m.cruise(w, 0.8, a));
  const lrc = cruiseGrid(CRUISE_LEVELS, WEIGHTS, (w, a) => m.longRangeCruise(w, a));
  const kias280 = cruiseGrid(LOW_LEVELS, WEIGHTS, (w, a) => m.cruise(w, m.machFromCas(280 * m.KT, a.p), a));
  // temperature coefficients from the model at FL330, 70 t
  const base = m.cruise(70000, 0.8, m.air(33000));
  const warm = m.cruise(70000, 0.8, m.air(33000, 15));
  const ffPercentPer3C = r1(((warm.fuelFlowKgPerHour / base.fuelFlowKgPerHour - 1) * 100) / 5);
  const tasKtPerC = r1((warm.tasKt - base.tasKt) / 15);
  const integrated = INTEGRATED_LEVELS.map((fl) => {
    const a = m.air(fl * 100);
    // cumulative nam from the heaviest weight down, trapezoid rule on nam/kg
    const nam: number[] = new Array(INTEGRATED_WEIGHTS.length).fill(0);
    for (let i = INTEGRATED_WEIGHTS.length - 2; i >= 0; i--) {
      const w1 = INTEGRATED_WEIGHTS[i + 1], w0 = INTEGRATED_WEIGHTS[i];
      const s = 0.5 * (m.cruise(w1, 0.8, a).narPerKg + m.cruise(w0, 0.8, a).narPerKg);
      nam[i] = nam[i + 1] + s * (w1 - w0);
    }
    return nam.map(r0);
  });
  return {
    ...HEADER,
    title: 'Section 3 Cruise',
    weightsKg: WEIGHTS,
    m080: {
      title: 'Table 3.1 Cruise at M 0.80: fuel flow (kg/h, three engines) by FL and gross weight; TAS (kt) ISA',
      fl: CRUISE_LEVELS,
      ff: m080.ff,
      tasIsa: CRUISE_LEVELS.map((fl) => r0(m.tasKtFromMach(0.8, m.air(fl * 100)))),
      corrections: { ffPercentPer3C, tasKtPerC },
    },
    lrc: {
      title: 'Table 3.2 Long range cruise: Mach, TAS (kt, ISA) and fuel flow (kg/h) by FL and gross weight',
      fl: CRUISE_LEVELS,
      mach: lrc.mach,
      tas: lrc.tas,
      ff: lrc.ff,
      corrections: { ffPercentPer3C, tasKtPerC },
    },
    kias280: {
      title: 'Table 3.3 Cruise at 280 KIAS: Mach, TAS (kt, ISA) and fuel flow (kg/h) by FL and gross weight',
      fl: LOW_LEVELS,
      mach: kias280.mach,
      tas: kias280.tas,
      ff: kias280.ff,
      corrections: { ffPercentPer3C, tasKtPerC },
    },
    integratedRange: {
      title: 'Table 3.4 Integrated range at M 0.80, ISA: nautical air miles from 86,000 kg',
      fl: INTEGRATED_LEVELS,
      weightsKg: INTEGRATED_WEIGHTS,
      /** nam[flIndex][weightIndex]; distance between two weights is the difference. */
      nam: integrated,
    },
    notes: [
      'Enter fuel-flow tables with the estimated mid-zone weight to the nearest 1,000 kg and interpolate between the 2,000 kg columns.',
      'ISA deviation for fuel flow: round to the nearest multiple of 3 °C, then apply the correction per 3 °C.',
      'TAS at constant Mach rises with temperature: add the correction per °C above ISA.',
      'A blank means the weight cannot be held in level flight at that level.',
    ],
  };
}

export function descentTables() {
  const table = DESCENT_WEIGHTS.map((w) => DESCENT_LEVELS.map((fl) => {
    const leg = m.descent(w, fl, 0);
    return { t: r0(leg.timeMin), f: r10(leg.fuelKg), d: r0(leg.distNm) };
  }));
  return {
    ...HEADER,
    title: 'Table 4.1 Descent 0.80M/280/250 KIAS, idle thrust, to 1,500 ft overhead: time (min), fuel (kg), distance (nam)',
    schedule: m.DESCENT_SCHEDULE,
    landingWeightKg: DESCENT_WEIGHTS,
    fl: DESCENT_LEVELS,
    /** table[weightIndex][flIndex] */
    table,
    approachAndLandingKg: 350,
    approachAndLandingMin: 6,
    notes: [
      'Enter with landing weight rounded to the nearest 10,000 kg (64,999 → 60,000; 65,000 → 70,000). No interpolation.',
      'Wind for the descent: the forecast level closest to half the height of the final cruise level.',
      'Descent from one level to another: difference of the two rows.',
      'Add the approach and landing allowance of 350 kg (6 min, no distance) from 1,500 ft to touchdown.',
    ],
  };
}

export function holdingTables() {
  const grid = (levels: number[], oneInop: boolean) => levels.map((fl) => WEIGHTS.map((w) => {
    const pt = m.holding(w, m.air(fl * 100), oneInop ? m.CLEAN_1INOP : m.CLEAN);
    const thrust = oneInop ? 2 * m.maxClimbThrustN(m.air(fl * 100)) : 3 * m.maxCruiseThrustN(m.air(fl * 100));
    if (pt.dragN > thrust) return null;
    return { ff: r0(pt.fuelFlowKgPerHour), tas: r0(pt.tasKt), kias: r0(pt.kias) };
  }));
  return {
    ...HEADER,
    title: 'Table 4.2 Holding, clean, 1.12 × minimum-drag speed: fuel flow (kg/h) and TAS (kt), ISA',
    weightsKg: WEIGHTS,
    /** FL15 is 1,500 ft */
    fl: HOLDING_LEVELS,
    table: grid(HOLDING_LEVELS, false),
    oneInop: { title: 'Table 5.9 Holding, one engine inoperative', fl: ONE_INOP_HOLDING_LEVELS, table: grid(ONE_INOP_HOLDING_LEVELS, true) },
    corrections: { ffPercentPer5C: 1.0 },
    notes: [
      'Enter with the estimated mid-hold weight to the nearest 1,000 kg and interpolate.',
      'ISA deviation to the nearest 5 °C; fuel flow +1% per 5 °C above ISA, −1% per 5 °C below.',
    ],
  };
}

export function abnormalTables() {
  const isaList = [-10, 0, 10, 20];
  const ceiling = isaList.map((isa) => WEIGHTS.map((w) => Math.floor(m.oneInopCeilingFt(w, isa) / 1000) * 10));
  const lrc = cruiseGrid(ONE_INOP_LEVELS, WEIGHTS, (w, a) => {
    // one engine inoperative cruises at max continuous thrust on two engines
    const pt = m.longRangeCruise(w, a, m.CLEAN_1INOP);
    return m.residualClimbFpm(w, pt.mach, a, 2 * m.maxClimbThrustN(a), m.CLEAN_1INOP) >= 100 ? pt : null;
  });
  const driftdown = DRIFTDOWN_FROM.map((fl) => CLIMB_WEIGHTS.map((w) => {
    const d = m.driftdown(w, fl, 0);
    return d.levelOffFt >= fl * 100 ? null : { t: r0(d.timeMin), f: r10(d.fuelKg), d: r0(d.distNm), fl: Math.floor(d.levelOffFt / 1000) * 10 };
  }));
  const dp = cruiseGrid(DP_LEVELS, WEIGHTS, (w, a) => m.longRangeCruise(w, a));
  const dp280 = cruiseGrid([100], WEIGHTS, (w, a) => m.cruise(w, m.machFromCas(280 * m.KT, a.p), a));
  return {
    ...HEADER,
    title: 'Section 5 Abnormal operations',
    weightsKg: WEIGHTS,
    oneInop: {
      ceiling: {
        title: 'Table 5.2 One engine inoperative altitude capability: ceiling (FL, 100 ft/min at drift-down speed, max continuous thrust) by gross weight and ISA deviation',
        isaDev: isaList,
        /** fl[isaIndex][weightIndex] */
        fl: ceiling,
      },
      lrc: { title: 'Table 5.3 One engine inoperative long range cruise: Mach, TAS (kt, ISA), fuel flow (kg/h, two engines)', fl: ONE_INOP_LEVELS, ...lrc },
      driftdown: {
        title: 'Table 5.4 Drift-down at max continuous thrust to 2,000 ft below the ceiling: time (min), fuel (kg), distance (nam), level-off FL',
        fromFl: DRIFTDOWN_FROM,
        weightsKg: CLIMB_WEIGHTS,
        /** table[fromIndex][weightIndex] */
        table: driftdown,
      },
    },
    depressurised: {
      lrc: { title: 'Table 5.10 Depressurised cruise, long range cruise at FL100 and FL140: Mach, TAS (kt, ISA), fuel flow (kg/h)', fl: DP_LEVELS, ...dp },
      kias280: { title: 'Table 5.11 Depressurised cruise at 280 KIAS, FL100', fl: [100], ...dp280 },
    },
    notes: [
      'Enter the ceiling table with gross weight to the nearest 1,000 kg and ISA deviation to the nearest 5 °C (interpolate between the 10 °C columns).',
      '1-INOP cruise may be taken to start at the weight and time of failure with an instantaneous descent to the 1-INOP level (CASA information book 4.2.9.8).',
      'Select the 1-INOP level at the weight at failure; select speed at the estimated mid-zone weight.',
    ],
  };
}

export function takeoffTables() {
  const fieldLimit = m.TAKEOFF_FLAPS.map((f) => TAKEOFF_PA.map((pa) => TAKEOFF_OAT.map((oat) => TAKEOFF_LENGTHS.map((len) => down100(Math.min(m.fieldLimitedWeightKg(len, f, pa, oat), 99000))))));
  const climbLimit = m.TAKEOFF_FLAPS.map((f) => TAKEOFF_PA.map((pa) => TAKEOFF_OAT.map((oat) => down100(Math.min(m.climbLimitedWeightKg(f, pa, oat), 99000)))));
  return {
    ...HEADER,
    title: 'Section 6 Take-off performance',
    flaps: m.TAKEOFF_FLAPS,
    pressureAltFt: TAKEOFF_PA,
    oatC: TAKEOFF_OAT,
    fieldLengthM: TAKEOFF_LENGTHS,
    fieldLimit: {
      title: 'Table 6.1 Field-length-limited brake-release weight (kg) by corrected field length, pressure altitude and OAT',
      /** weightKg[flapIndex][paIndex][oatIndex][lengthIndex] */
      weightKg: fieldLimit,
    },
    climbLimit: {
      title: 'Table 6.2 Climb-limited brake-release weight (kg): second segment 2.7%, one engine inoperative',
      /** weightKg[flapIndex][paIndex][oatIndex] */
      weightKg: climbLimit,
      tailwindKgPerKt: 300,
      engineAntiIceKg: 1000,
      engineAndWingAntiIceKg: 3500,
    },
    corrections: m.RUNWAY_CORRECTIONS.takeoff,
    weightLapseAbove2000FtKgPer1000Ft: 50,
    notes: [
      'Corrected field length = (TORA − 50 m line-up) × (1 − 0.06 × uphill slope %) + 10 m per knot of headwind, or − 35 m per knot of tailwind.',
      'Pressure altitude = elevation + 27 ft per hPa below 1013.',
      'Performance-limited weight is the lowest of the field, climb and structural limits. Structural limits must not be exceeded.',
      'Take-off speeds: Table 1.3 at the brake-release weight and flap.',
    ],
  };
}

export function landingTables() {
  const fieldLimit = m.LANDING_FLAPS.map((f) => [false, true].map((wet) => LANDING_PA.map((pa) => LANDING_LENGTHS.map((len) => down100(Math.min(m.landingFieldLimitedWeightKg(len, f, pa, wet), 99000))))));
  const approachClimb = m.LANDING_FLAPS.map((f) => LANDING_PA.map((pa) => LANDING_OAT.map((oat) => down100(Math.min(m.approachClimbLimitedWeightKg(f, pa, oat), 99000)))));
  return {
    ...HEADER,
    title: 'Section 6 Landing performance',
    flaps: m.LANDING_FLAPS,
    pressureAltFt: LANDING_PA,
    oatC: LANDING_OAT,
    fieldLengthM: LANDING_LENGTHS,
    surfaces: ['dry', 'wet'],
    fieldLimit: {
      title: 'Table 6.4 Field-length-limited landing weight (kg) by corrected landing distance, surface and pressure altitude',
      /** weightKg[flapIndex][surfaceIndex][paIndex][lengthIndex] */
      weightKg: fieldLimit,
    },
    approachClimb: {
      title: 'Table 6.5 Approach-climb-limited landing weight (kg): 2.4%, one engine inoperative, go-around flap',
      /** weightKg[flapIndex][paIndex][oatIndex] */
      weightKg: approachClimb,
    },
    corrections: m.RUNWAY_CORRECTIONS.landing,
    notes: [
      'Corrected landing distance = LDA × (1 + 0.04 × downhill slope %) + 8 m per knot of headwind, or − 40 m per knot of tailwind.',
      'Wet: the factored dry distance × 1.15. The dry table may be entered with the corrected distance ÷ 1.15.',
      'Maximum landing weight is the lowest of the field, approach-climb and structural limits.',
    ],
  };
}

export function balanceTables() {
  const fuelIndex = FUEL_INDEX_STEPS.map((kg) => {
    const d = m.fuelDistribution(kg);
    return { kg, iu: r1(m.fuelIndex(kg)), wingKg: r0(d.wingKg), centreKg: r0(d.centreKg), aftAuxKg: r0(d.aftAuxKg), fwdAuxKg: r0(d.fwdAuxKg) };
  });
  const envelope = range(40000, 86000, 2000).map((kg) => {
    const l = m.cgLimits(kg);
    return { kg, forwardMac: r1(l.forwardMac), aftMac: r1(l.aftMac) };
  });
  const trim = range(10, 40, 2).map((mac) => ({ mac, flaps5: m.stabTrimUnits(mac, 5), flaps15: m.stabTrimUnits(mac, 15), flaps25: m.stabTrimUnits(mac, 25) }));
  return {
    ...HEADER,
    title: 'Section 7 Weight and balance',
    datum: 'Nose of the aeroplane. Arms in metres aft of the datum.',
    mac: { lemacM: m.AIRCRAFT.wing.lemacM, macM: m.AIRCRAFT.wing.macM },
    indexUnit: {
      definition: `IU = ${m.BALANCE.indexOffset} + weight (kg) × (arm − ${m.BALANCE.referenceArmM.toFixed(2)} m) ÷ ${m.BALANCE.indexDivisor}`,
      referenceArmM: m.BALANCE.referenceArmM,
      offset: m.BALANCE.indexOffset,
      divisor: m.BALANCE.indexDivisor,
    },
    zones: m.BALANCE.zones,
    compartments: m.BALANCE.compartments,
    holdFloorKgPerM2: m.BALANCE.holdFloorKgPerM2,
    tanks: m.BALANCE.tanks,
    crewSeatArmM: m.BALANCE.crewSeatArmM,
    extraCrewKg: m.BALANCE.extraCrewKg,
    typicalBasicWeightKg: m.AIRCRAFT.weights.basicWeightKg,
    typicalBasicIndex: m.BALANCE.typicalBasicIndex,
    standardWeights: m.BALANCE.standardWeights,
    envelope: { points: m.BALANCE.envelope, table: envelope },
    fuelIndex,
    stabTrim: trim,
    notes: [
      'Index units are positive aft of 25% MAC and negative forward of it.',
      'Passenger zones are entered with equivalent adults: an adolescent or child counts as half an adult for the scale; infants move nothing. Weights are always the actual standard weights.',
      'Check the CG at zero fuel weight and at brake-release weight; both must lie inside the envelope.',
      'Fuel burns from tank 2 first, then tank to engine; the fuel index table gives the index of the fuel on board at any weight.',
    ],
  };
}

export function generateAll(dir: string) {
  mkdirSync(dir, { recursive: true });
  const files: Record<string, unknown> = {
    'limitations.json': limitations(),
    'fuel-policy.json': fuelPolicy(),
    'climb.json': climbTables(),
    'altitude-capability.json': altitudeCapability(),
    'cruise.json': cruiseTables(),
    'descent.json': descentTables(),
    'holding.json': holdingTables(),
    'abnormal.json': abnormalTables(),
    'takeoff.json': takeoffTables(),
    'landing.json': landingTables(),
    'balance.json': balanceTables(),
  };
  for (const [name, data] of Object.entries(files)) {
    writeFileSync(`${dir}/${name}`, JSON.stringify(data, null, 1) + '\n');
  }
  return Object.keys(files);
}

if (process.argv[1] && process.argv[1].endsWith('generate.ts')) {
  const dir = new URL('./data/', import.meta.url).pathname;
  const names = generateAll(dir);
  console.log(`wrote ${names.length} tables to ${dir}`);
}
