import {test,expect} from '@playwright/test';
test.setTimeout(90_000);
test('photo terrain is optional, renders on the shared map, and survives cached offline reuse',async({page,context},info)=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1280,height:720});
 await page.goto('/history?event=everest-1953&terrain=photo');
 const stage=page.locator('[data-map-ready=true]');await stage.waitFor();
 await page.getByRole('button',{name:'Pause',exact:true}).click();
 await expect(stage).toHaveAttribute('data-terrain-imagery','ready',{timeout:30_000});
 await page.waitForTimeout(1500);
 const plate=()=>stage.evaluate(async(e:any)=>{const p=await e.chartApi.readPlate();const out:number[]=[];if(p)for(let i=0;i<p.data.length;i+=64)out.push(p.data[i]);return out;});
 const photo=await plate();expect(photo.length).toBeGreaterThan(100);
 await page.screenshot({path:info.outputPath('photo-laptop.png')});
 await page.getByRole('button',{name:'Data sources',exact:true}).click();
 await expect(page.locator('.map-sources')).toContainText('2026-10-03');
 await page.getByRole('checkbox',{name:'Photo terrain',exact:true}).uncheck();
 await expect(stage).toHaveAttribute('data-terrain-imagery','off');
 const plain=await plate();expect(plain.filter((v,i)=>Math.abs(v-photo[i])>10).length).toBeGreaterThan(100);
 await context.setOffline(true);
 await page.getByRole('checkbox',{name:'Photo terrain',exact:true}).check();
 await expect(stage).toHaveAttribute('data-terrain-imagery','ready',{timeout:30_000});
 await context.setOffline(false);
 await page.keyboard.press('Escape');
 await page.evaluate(()=>document.documentElement.classList.add('dark'));
 await page.screenshot({path:info.outputPath('photo-dark.png')});
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);
 await page.screenshot({path:info.outputPath('photo-phone.png')});
 await page.getByRole('link',{name:'Present day',exact:true}).click();
 await page.waitForURL(url=>url.pathname==='/');
 await expect(stage).toHaveAttribute('data-terrain-imagery','ready',{timeout:30_000});
 expect(errors).toEqual([]);
});
test('photo failure leaves the ordinary terrain usable and no banner',async({page})=>{
 await page.route('**/history/imagery/*.png',route=>route.fulfill({status:404,body:''}));
 await page.goto('/history?event=everest-1953&terrain=photo');
 const stage=page.locator('[data-map-ready=true]');await stage.waitFor();
 await expect(stage).toHaveAttribute('data-terrain-imagery','unavailable',{timeout:30_000});
 await page.getByRole('button',{name:'Zoom in',exact:true}).click();
 await page.getByRole('button',{name:'Data sources',exact:true}).click();
 await expect(page.locator('.map-sources')).toContainText('Imagery unavailable');
});
