#!/usr/bin/env node
// Deterministically trim/pack the approved phase-1 art. No art generation or downloads.
import { createRequire } from 'node:module';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
const require = createRequire(import.meta.url);
const { createCanvas, loadImage } = require(process.env.CANVAS_MODULE || '@napi-rs/canvas');
const crops = { cumulus: ['painted-atlas',840,98,696,355], cumulonimbus: ['painted-atlas',0,533,768,442], cirrus: ['painted-atlas',813,597,710,343], stratus: ['stratus',0,0,2048,210], nimbostratus: ['nimbostratus',0,0,1981,794] };
const sprites = [], rects = {};
let nextY = 2;
for (const [genus,[file,x,y,w,h]] of Object.entries(crops)) {
  const image = await loadImage(`tools/clouds/assets/${file}.webp`);
  const c = createCanvas(w,h), ctx=c.getContext('2d'); ctx.drawImage(image,x,y,w,h,0,0,w,h);
  const pixels = ctx.getImageData(0,0,w,h).data;
  let x0=w,y0=h,x1=-1,y1=-1;
  for (let py=0;py<h;py++) for(let px=0;px<w;px++) if(pixels[(py*w+px)*4+3]>=32) {
    x0=Math.min(x0,px);x1=Math.max(x1,px);y0=Math.min(y0,py);y1=Math.max(y1,py);
  }
  const sw=x1-x0+1,sh=y1-y0+1,scale=Math.min(1,768/sw),dw=Math.round(sw*scale),dh=Math.round(sh*scale);
  sprites.push({ c,x0,y0,sw,sh,dw,dh,y:nextY }); rects[genus]=[2,nextY,dw,dh]; nextY+=dh+4;
}
const packed=createCanvas(772,nextY),ctx=packed.getContext('2d');
for(const s of sprites) ctx.drawImage(s.c,s.x0,s.y0,s.sw,s.sh,2,s.y,s.dw,s.dh);
const bytes=await packed.encode('webp',90);
mkdirSync('web/public/sky',{recursive:true});
writeFileSync('web/public/sky/painted-clouds.webp',bytes);
writeFileSync('training/src/sky/atlas.ts',`// Generated by tools/clouds/pack-painted.mjs from the approved phase-1 WebPs.\nexport const SPRITE_RECTS = ${JSON.stringify(rects,null,2)} as const;\n`);
const report={width:packed.width,height:packed.height,bytes:bytes.length,decodedBytes:packed.width*packed.height*4,retainedPaletteBytes:packed.width*packed.height*4*3,sha256:createHash('sha256').update(bytes).digest('hex'),sourceBytes:JSON.parse(readFileSync('tools/clouds/assets/manifest.json')).reduce((sum,a)=>sum+a.bytes,0),rects};
writeFileSync('tools/clouds/assets/production-manifest.json',JSON.stringify(report,null,2)+'\n');
console.log(report);
